var h;h||=typeof Module != 'undefined' ? Module : {};h.zf||(h.zf=0);h.zf++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;"undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a||function(b){function c(p,r,u){var v=new XMLHttpRequest;v.open("GET",p,!0);v.responseType="arraybuffer";v.onprogress=function(B){var C=r;B.total&&(C=B.total);if(B.loaded){v.Je?h.af[p].loaded=B.loaded:(v.Je=!0,h.af||(h.af={}),h.af[p]={loaded:B.loaded,total:C});var F=C=B=0,W;for(W in h.af){var cb=h.af[W];B+=cb.total;C+=cb.loaded;F++}B=Math.ceil(B*
h.zf/F);h.setStatus?.(`Downloading data... (${C}/${B})`)}else h.af||h.setStatus?.("Downloading data...")};v.onerror=function(){throw Error("NetworkError for: "+p);};v.onload=function(){if(200==v.status||304==v.status||206==v.status||0==v.status&&v.response)u(v.response);else throw Error(v.statusText+" : "+v.responseURL);};v.send(null)}function d(p){console.error("package error:",p)}function e(p){function r(C,F,W){this.start=C;this.end=F;this.audio=W}function u(C){if(!C)throw"Loading data file failed."+
Error().stack;if(C.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;C=new Uint8Array(C);r.prototype.wf=C;C=b.files;for(var F=0;F<C.length;++F)r.prototype.Je[C[F].filename].onload();p.removeRunDependency("datafile_index.data")}p.FS_createPath("/","data",!0,!0);p.FS_createPath("/data","images",!0,!0);p.FS_createPath("/data","music",!0,!0);p.FS_createPath("/data","sounds",!0,!0);r.prototype={Je:{},open:function(C,F){this.name=F;this.Je[F]=this;p.addRunDependency(`fp ${this.name}`)},
onload:function(){this.finish(this.wf.subarray(this.start,this.end))},finish:function(C){p.FS_createDataFile(this.name,null,C,!0,!0,!0);p.removeRunDependency(`fp ${this.name}`);this.Je[this.name]=null}};for(var v=b.files,B=0;B<v.length;++B)(new r(v[B].start,v[B].end,v[B].audio||0)).open("GET",v[B].filename);p.addRunDependency("datafile_index.data");p.Yf||(p.Yf={});p.Yf["index.data"]={Pg:!1};n?(u(n),n=null):m=u}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,
window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var f=h.locateFile?h.locateFile("index.data",
""):"index.data",g=b.remote_package_size,m=null,n=h.getPreloadedPackage?h.getPreloadedPackage(f,g):null;n||c(f,g,function(p){m?(m(p),m=null):n=p},d);h.calledRun?e(h):(h.preRun||(h.preRun=[]),h.preRun.push(e))}({files:[{filename:"/data/images/redspot.jpg",start:0,end:9909},{filename:"/data/music/decision.s3m",start:9909,end:127289},{filename:"/data/sounds/ast1.wav",start:127289,end:133281,audio:1},{filename:"/data/sounds/ast2.wav",start:133281,end:144126,audio:1},{filename:"/data/sounds/ast3.wav",
start:144126,end:168664,audio:1},{filename:"/data/sounds/ast4.wav",start:168664,end:193202,audio:1},{filename:"/data/sounds/bullet.wav",start:193202,end:199468,audio:1},{filename:"/data/sounds/explode.wav",start:199468,end:223E3,audio:1},{filename:"/data/sounds/extralife.wav",start:223E3,end:278974,audio:1},{filename:"/data/sounds/gameover.wav",start:278974,end:319942,audio:1},{filename:"/data/sounds/thrust.wav",start:319942,end:353086,audio:1}],remote_package_size:353086})})();
var aa=Object.assign({},h),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="",fa;"undefined"!=typeof document&&document.currentScript&&(ea=document.currentScript.src);ea=ea.startsWith("blob:")?"":ea.substr(0,ea.replace(/[?#].*/,"").lastIndexOf("/")+1);fa=a=>fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var ha=h.print||console.log.bind(console),k=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);
h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);var ia;h.wasmBinary&&(ia=h.wasmBinary);var ja,ka=!1,la,l,q,ma,na,t,w,x,y,oa=[],pa=[],qa=[],ra=[];function sa(){var a=h.preRun.shift();oa.unshift(a)}var ta=0,ua=null,va=null;function wa(){ta++;h.monitorRunDependencies?.(ta)}function xa(){ta--;h.monitorRunDependencies?.(ta);if(0==ta&&(null!==ua&&(clearInterval(ua),ua=null),va)){var a=va;va=null;a()}}
function z(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);ka=!0;la=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ya=a=>a.startsWith("data:application/octet-stream;base64,"),za;function Aa(a){if(a==za&&ia)return new Uint8Array(ia);throw"both async and sync fetching of the wasm failed";}function Ba(a){return ia?Promise.resolve().then(()=>Aa(a)):fa(a).then(b=>new Uint8Array(b),()=>Aa(a))}
function Ca(a,b,c){return Ba(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{k(`failed to asynchronously prepare wasm: ${d}`);z(d)})}function Da(a,b){var c=za;ia||"function"!=typeof WebAssembly.instantiateStreaming||ya(c)||"function"!=typeof fetch?Ca(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){k(`wasm streaming compile failed: ${e}`);k("falling back to ArrayBuffer instantiation");return Ca(c,a,b)}))}
var Ea,Fa,Ma={266076:a=>{a=(a?A(q,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");return Ga(Ha(a),"i8",Ia)},266301:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,266448:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,266682:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio=
{};b.Ie||("undefined"!==typeof AudioContext?b.Ie=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.Ie=new webkitAudioContext),b.Ie&&Ja(b.Ie));return void 0===b.Ie?-1:0},267175:()=>h.SDL2.Ie.sampleRate,267243:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.gf&&(clearTimeout(g.capture.gf),g.capture.gf=void 0);g.capture.qf=g.Ie.createMediaStreamSource(m);g.capture.Me=g.Ie.createScriptProcessor(b,a,1);g.capture.Me.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),
g.capture.yf=n.inputBuffer,Ka(c,[d]))};g.capture.qf.connect(g.capture.Me);g.capture.Me.connect(g.Ie.destination);g.capture.stream=m}var g=h.SDL2;g.capture.tf=g.Ie.createBuffer(a,b,g.Ie.sampleRate);g.capture.tf.getChannelData(0).fill(0);g.capture.gf=setTimeout(function(){g.capture.yf=g.capture.tf;Ka(c,[d])},b/g.Ie.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&
navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},268895:(a,b,c,d)=>{var e=h.SDL2;e.audio.Me=e.Ie.createScriptProcessor(b,0,a);e.audio.Me.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Mf=f.outputBuffer,Ka(c,[d]))};e.audio.Me.connect(e.Ie.destination)},269305:(a,b)=>{for(var c=h.SDL2,d=c.capture.yf.numberOfChannels,e=0;e<d;++e){var f=c.capture.yf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+
b+" samples!";if(1==d)for(var g=0;g<b;++g)La(a+4*g,f[g]);else for(g=0;g<b;++g)La(a+4*(g*d+e),f[g])}},269910:(a,b)=>{for(var c=h.SDL2,d=c.audio.Mf.numberOfChannels,e=0;e<d;++e){var f=c.audio.Mf.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=x[a+(g*d+e<<2)>>2]}},270390:a=>{var b=h.SDL2;if(a){void 0!==b.capture.gf&&clearTimeout(b.capture.gf);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();
for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.Me&&(b.capture.Me.onaudioprocess=function(){},b.capture.Me.disconnect(),b.capture.Me=void 0);void 0!==b.capture.qf&&(b.capture.qf.disconnect(),b.capture.qf=void 0);void 0!==b.capture.tf&&(b.capture.tf=void 0);b.capture=void 0}else void 0!=b.audio.Me&&(b.audio.Me.disconnect(),b.audio.Me=void 0),b.audio=void 0;void 0!==b.Ie&&void 0===b.audio&&void 0===b.capture&&(b.Ie.close(),b.Ie=void 0)},271562:()=>
window.innerWidth,271592:()=>window.innerHeight,271623:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.fg!==h.canvas&&(d.Re=h.createContext(h.canvas,!1,!0),d.fg=h.canvas);if(d.w!==a||d.h!==b||d.og!==d.Re)d.image=d.Re.createImageData(a,b),d.w=a,d.h=b,d.og=d.Re;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=t[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.ig!==a&&(d.hg=new Int32Array(a.buffer),
d.jg=new Uint8Array(a.buffer),d.ig=a),a=d.hg,c=a.length,a.set(t.subarray(b,b+c)),a=d.jg,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Re.putImageData(d.image,0,0)},273092:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&
b instanceof CanvasPixelArray)for(n=b.length;m<n;){var p=t[e];b[m]=p&255;b[m+1]=p>>8&255;b[m+2]=p>>16&255;b[m+3]=p>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(t.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=D(c.length+1);E(c,q,d,c.length+1);return d},274081:a=>{h.canvas&&(h.canvas.style.cursor=a?A(q,a):"")},274164:()=>{h.canvas&&(h.canvas.style.cursor="none")}};
function Na(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Oa=a=>{for(;0<a.length;)a.shift()(h)},Pa=h.noExitRuntime||!0;
function La(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":l[a]=b;break;case "i8":l[a]=b;break;case "i16":ma[a>>1]=b;break;case "i32":t[a>>2]=b;break;case "i64":z("to do setValue(i64) use WASM_BIGINT");case "float":x[a>>2]=b;break;case "double":y[a>>3]=b;break;case "*":w[a>>2]=b;break;default:z(`invalid type for setValue: ${c}`)}}function Qa(){var a=t[+Ra>>2];Ra+=4;return a}
var Sa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ta=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Sa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ua=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Va=a=>{if("/"===
a)return"/";a=Ta(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Wa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);z("initRandomDevice")},Xa=a=>(Xa=Wa())(a),Ya=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Sa(b.split("/").filter(e=>!!e),!c).join("/");
return(c?"/":"")+b||"."},Za="undefined"!=typeof TextDecoder?new TextDecoder:void 0,A=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Za)return Za.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
$a=[],ab=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},E=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&
63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function Ha(a,b){var c=Array(ab(a)+1);a=E(a,c,0,c.length);b&&(c.length=a);return c}var bb=[];function db(a,b){bb[a]={input:[],Le:[],Ve:b};eb(a,fb)}
var fb={open(a){var b=bb[a.node.sf];if(!b)throw new G(43);a.Ge=b;a.seekable=!1},close(a){a.Ge.Ve.lf(a.Ge)},lf(a){a.Ge.Ve.lf(a.Ge)},read(a,b,c,d){if(!a.Ge||!a.Ge.Ve.Pf)throw new G(60);for(var e=0,f=0;f<d;f++){try{var g=a.Ge.Ve.Pf(a.Ge)}catch(m){throw new G(29);}if(void 0===g&&0===e)throw new G(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.Ge||!a.Ge.Ve.Df)throw new G(60);try{for(var e=0;e<d;e++)a.Ge.Ve.Df(a.Ge,b[c+e])}catch(f){throw new G(29);
}d&&(a.node.timestamp=Date.now());return e}},gb={Pf(){a:{if(!$a.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}$a=Ha(a,!0)}a=$a.shift()}return a},Df(a,b){null===b||10===b?(ha(A(a.Le,0)),a.Le=[]):0!=b&&a.Le.push(b)},lf(a){a.Le&&0<a.Le.length&&(ha(A(a.Le,0)),a.Le=[])},rg(){return{Gg:25856,Ig:5,Fg:191,Hg:35387,Eg:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},sg(){return 0},
tg(){return[24,80]}},hb={Df(a,b){null===b||10===b?(k(A(a.Le,0)),a.Le=[]):0!=b&&a.Le.push(b)},lf(a){a.Le&&0<a.Le.length&&(k(A(a.Le,0)),a.Le=[])}};function ib(a,b){var c=a.Kd?a.Kd.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Kd,a.Kd=new Uint8Array(b),0<a.He&&a.Kd.set(c.subarray(0,a.He),0))}
var H={Se:null,Ue(){return H.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new G(63);H.Se||(H.Se={dir:{node:{Ye:H.Ee.Ye,Ne:H.Ee.Ne,df:H.Ee.df,rf:H.Ee.rf,$f:H.Ee.$f,vf:H.Ee.vf,ag:H.Ee.ag,Zf:H.Ee.Zf,uf:H.Ee.uf},stream:{$e:H.Fe.$e}},file:{node:{Ye:H.Ee.Ye,Ne:H.Ee.Ne},stream:{$e:H.Fe.$e,read:H.Fe.read,write:H.Fe.write,If:H.Fe.If,Cf:H.Fe.Cf,Vf:H.Fe.Vf}},link:{node:{Ye:H.Ee.Ye,Ne:H.Ee.Ne,ff:H.Ee.ff},stream:{}},Lf:{node:{Ye:H.Ee.Ye,Ne:H.Ee.Ne},stream:jb}});
c=kb(a,b,c,d);I(c.mode)?(c.Ee=H.Se.dir.node,c.Fe=H.Se.dir.stream,c.Kd={}):32768===(c.mode&61440)?(c.Ee=H.Se.file.node,c.Fe=H.Se.file.stream,c.He=0,c.Kd=null):40960===(c.mode&61440)?(c.Ee=H.Se.link.node,c.Fe=H.Se.link.stream):8192===(c.mode&61440)&&(c.Ee=H.Se.Lf.node,c.Fe=H.Se.Lf.stream);c.timestamp=Date.now();a&&(a.Kd[b]=c,a.timestamp=c.timestamp);return c},Rg(a){return a.Kd?a.Kd.subarray?a.Kd.subarray(0,a.He):new Uint8Array(a.Kd):new Uint8Array(0)},Ee:{Ye(a){var b={};b.Mg=8192===(a.mode&61440)?a.id:
1;b.Tg=a.id;b.mode=a.mode;b.Yg=1;b.uid=0;b.Sg=0;b.sf=a.sf;I(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.He:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Cg=new Date(a.timestamp);b.Wg=new Date(a.timestamp);b.Lg=new Date(a.timestamp);b.eg=4096;b.Dg=Math.ceil(b.size/b.eg);return b},Ne(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.He!=b))if(0==b)a.Kd=null,a.He=0;else{var c=a.Kd;a.Kd=new Uint8Array(b);c&&a.Kd.set(c.subarray(0,
Math.min(b,a.He)));a.He=b}},df(){throw lb[44];},rf(a,b,c,d){return H.createNode(a,b,c,d)},$f(a,b,c){if(I(a.mode)){try{var d=mb(b,c)}catch(f){}if(d)for(var e in d.Kd)throw new G(55);}delete a.parent.Kd[a.name];a.parent.timestamp=Date.now();a.name=c;b.Kd[c]=a;b.timestamp=a.parent.timestamp},vf(a,b){delete a.Kd[b];a.timestamp=Date.now()},ag(a,b){var c=mb(a,b),d;for(d in c.Kd)throw new G(55);delete a.Kd[b];a.timestamp=Date.now()},Zf(a){var b=[".",".."],c;for(c of Object.keys(a.Kd))b.push(c);return b},
uf(a,b,c){a=H.createNode(a,b,41471,0);a.link=c;return a},ff(a){if(40960!==(a.mode&61440))throw new G(28);return a.link}},Fe:{read(a,b,c,d,e){var f=a.node.Kd;if(e>=a.node.He)return 0;a=Math.min(a.node.He-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Kd||a.Kd.subarray)){if(f)return a.Kd=b.subarray(c,c+d),a.He=d;if(0===a.He&&0===e)return a.Kd=b.slice(c,c+d),a.He=d;if(e+
d<=a.He)return a.Kd.set(b.subarray(c,c+d),e),d}ib(a,e+d);if(a.Kd.subarray&&b.subarray)a.Kd.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Kd[e+f]=b[c+f];a.He=Math.max(a.He,e+d);return d},$e(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.He);if(0>b)throw new G(28);return b},If(a,b,c){ib(a.node,b+c);a.node.He=Math.max(a.node.He,b+c)},Cf(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new G(43);a=a.node.Kd;if(e&2||a.buffer!==l.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,
c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;z();b=void 0;if(!b)throw new G(48);l.set(a,b)}else c=!1,b=a.byteOffset;return{bh:b,Ag:c}},Vf(a,b,c,d){H.Fe.write(a,b,0,d,c,!1);return 0}}},nb=(a,b,c)=>{var d=`al ${a}`;fa(a).then(e=>{b(new Uint8Array(e));d&&xa(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&wa(d)},ob=h.preloadPlugins||[],rb=(a,b,c,d)=>{"undefined"!=typeof pb&&qb();var e=!1;ob.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},tb=(a,b,c,d,e,f,g,
m,n,p)=>{function r(B){function C(F){p?.();m||sb(a,b,F,d,e,n);f?.();xa(v)}rb(B,u,C,()=>{g?.();xa(v)})||C(B)}var u=b?Ya(Ta(a+"/"+b)):a,v=`cp ${u}`;wa(v);"string"==typeof c?nb(c,r,g):r(c)},ub=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},vb=null,wb={},xb=[],yb=1,zb=null,Ab=!0,G=class{constructor(a){this.name="ErrnoError";this.Xe=a}},lb={},Bb=class{constructor(){this.Je={};this.node=null}get flags(){return this.Je.flags}set flags(a){this.Je.flags=a}get position(){return this.Je.position}set position(a){this.Je.position=
a}},Cb=class{constructor(a,b,c,d){a||=this;this.parent=a;this.Ue=a.Ue;this.ef=null;this.id=yb++;this.name=b;this.mode=c;this.Ee={};this.Fe={};this.sf=d}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get ug(){return I(this.mode)}get Rf(){return 8192===(this.mode&61440)}};
function Db(a,b={}){a=Ya(a);if(!a)return{path:"",node:null};b=Object.assign({Of:!0,Ef:0},b);if(8<b.Ef)throw new G(32);a=a.split("/").filter(g=>!!g);for(var c=vb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=mb(c,a[e]);d=Ta(d+"/"+a[e]);c.ef&&(!f||f&&b.Of)&&(c=c.ef.root);if(!f||b.Af)for(f=0;40960===(c.mode&61440);)if(c=Eb(d),d=Ya(Ua(d),c),c=Db(d,{Ef:b.Ef+1}).node,40<f++)throw new G(32);}return{path:d,node:c}}
function Fb(a){for(var b;;){if(a===a.parent)return a=a.Ue.Uf,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Gb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%zb.length}function mb(a,b){var c=I(a.mode)?(c=Hb(a,"x"))?c:a.Ee.df?0:2:54;if(c)throw new G(c);for(c=zb[Gb(a.id,b)];c;c=c.bf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ee.df(a,b)}
function kb(a,b,c,d){a=new Cb(a,b,c,d);b=Gb(a.parent.id,a.name);a.bf=zb[b];return zb[b]=a}function I(a){return 16384===(a&61440)}function Ib(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Hb(a,b){if(Ab)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Jb(a,b){try{return mb(a,b),20}catch(c){}return Hb(a,"wx")}function Kb(a){a=xb[a];if(!a)throw new G(8);return a}
function Lb(a,b=-1){a=Object.assign(new Bb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!xb[b])break a;throw new G(33);}a.fd=b;return xb[b]=a}function Mb(a,b=-1){a=Lb(a,b);a.Fe?.Ng?.(a);return a}var jb={open(a){a.Fe=wb[a.node.sf].Fe;a.Fe.open?.(a)},$e(){throw new G(70);}};function eb(a,b){wb[a]={Fe:b}}
function Nb(a,b){var c="/"===b;if(c&&vb)throw new G(10);if(!c&&b){var d=Db(b,{Of:!1});b=d.path;d=d.node;if(d.ef)throw new G(10);if(!I(d.mode))throw new G(54);}b={type:a,ah:{},Uf:b,vg:[]};a=a.Ue(b);a.Ue=b;b.root=a;c?vb=a:d&&(d.ef=b,d.Ue&&d.Ue.vg.push(b))}function Ob(a,b,c){var d=Db(a,{parent:!0}).node;a=Va(a);if(!a||"."===a||".."===a)throw new G(28);var e=Jb(d,a);if(e)throw new G(e);if(!d.Ee.rf)throw new G(63);return d.Ee.rf(d,a,b,c)}function J(a){return Ob(a,16895,0)}
function Pb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Ob(a,b|8192,c)}function Qb(a,b){if(!Ya(a))throw new G(44);var c=Db(b,{parent:!0}).node;if(!c)throw new G(44);b=Va(b);var d=Jb(c,b);if(d)throw new G(d);if(!c.Ee.uf)throw new G(63);c.Ee.uf(c,b,a)}
function Rb(a){var b=Db(a,{parent:!0}).node;if(!b)throw new G(44);var c=Va(a);a=mb(b,c);a:{try{var d=mb(b,c)}catch(f){d=f.Xe;break a}var e=Hb(b,"wx");d=e?e:I(d.mode)?31:0}if(d)throw new G(d);if(!b.Ee.vf)throw new G(63);if(a.ef)throw new G(10);b.Ee.vf(b,c);b=Gb(a.parent.id,a.name);if(zb[b]===a)zb[b]=a.bf;else for(b=zb[b];b;){if(b.bf===a){b.bf=a.bf;break}b=b.bf}}function Eb(a){a=Db(a).node;if(!a)throw new G(44);if(!a.Ee.ff)throw new G(28);return Ya(Fb(a.parent),a.Ee.ff(a))}
function Sb(a,b){a="string"==typeof a?Db(a,{Af:!0}).node:a;if(!a.Ee.Ne)throw new G(63);a.Ee.Ne(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Tb(a,b,c){if(""===a)throw new G(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Ta(a);try{e=Db(a,{Af:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new G(20);}else e=Ob(a,c,0),d=!0;if(!e)throw new G(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!I(e.mode))throw new G(54);if(!d&&
(c=e?40960===(e.mode&61440)?32:I(e.mode)&&("r"!==Ib(b)||b&512)?31:Hb(e,Ib(b)):44))throw new G(c);if(b&512&&!d){c=e;c="string"==typeof c?Db(c,{Af:!0}).node:c;if(!c.Ee.Ne)throw new G(63);if(I(c.mode))throw new G(31);if(32768!==(c.mode&61440))throw new G(28);if(d=Hb(c,"w"))throw new G(d);c.Ee.Ne(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Lb({node:e,path:Fb(e),flags:b,seekable:!0,position:0,Fe:e.Fe,xg:[],error:!1});e.Fe.open&&e.Fe.open(e);!h.logReadFiles||b&1||(Ub||={},a in Ub||(Ub[a]=1));return e}
function Vb(a){if(null===a.fd)throw new G(8);a.Bf&&(a.Bf=null);try{a.Fe.close&&a.Fe.close(a)}catch(b){throw b;}finally{xb[a.fd]=null}a.fd=null}function Wb(a,b,c){if(null===a.fd)throw new G(8);if(!a.seekable||!a.Fe.$e)throw new G(70);if(0!=c&&1!=c&&2!=c)throw new G(28);a.position=a.Fe.$e(a,b,c);a.xg=[]}
function Xb(a,b,c,d,e,f){if(0>d||0>e)throw new G(28);if(null===a.fd)throw new G(8);if(0===(a.flags&2097155))throw new G(8);if(I(a.node.mode))throw new G(31);if(!a.Fe.write)throw new G(28);a.seekable&&a.flags&1024&&Wb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new G(70);b=a.Fe.write(a,b,c,d,e,f);g||(a.position+=b);return b}var Yb;
function Zb(a,b){a="string"==typeof a?a:Fb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ta(a+"/"+c);try{J(d)}catch(e){}a=d}}return d}function $b(a,b,c,d){a=Ta(("string"==typeof a?a:Fb(a))+"/"+b);c=ub(c,d);return Ob(a,(void 0!==c?c:438)&4095|32768,0)}
function sb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Fb(a),g=b?Ta(a+"/"+b):a);a=ub(d,e);g=Ob(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Sb(g,a|146);b=Tb(g,577);Xb(b,c,0,c.length,0,f);Vb(b);Sb(g,a)}}
function K(a,b,c,d){a=Ta(("string"==typeof a?a:Fb(a))+"/"+b);b=ub(!!c,!!d);K.Sf||(K.Sf=64);var e=K.Sf++<<8|0;eb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,m,n){for(var p=0,r=0;r<n;r++){try{var u=c()}catch(v){throw new G(29);}if(void 0===u&&0===p)throw new G(6);if(null===u||void 0===u)break;p++;g[m+r]=u}p&&(f.node.timestamp=Date.now());return p},write(f,g,m,n){for(var p=0;p<n;p++)try{d(g[m+p])}catch(r){throw new G(29);}n&&(f.node.timestamp=Date.now());return p}});return Pb(a,
b,e)}function ac(a){if(!(a.Rf||a.ug||a.link||a.Kd)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.Kd=(void 0)(a.url),a.He=a.Kd.length}catch(b){throw new G(29);}}}
function bc(a,b,c,d,e){if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={Rf:!1,url:c};var f=$b(a,b,d,e);c.Kd?f.Kd=c.Kd:c.url&&(f.Kd=null,f.url=c.url);Object.defineProperties(f,{He:{get:function(){return this.Kd.length}}});var g={};Object.keys(f.Fe).forEach(m=>{var n=f.Fe[m];g[m]=(...p)=>{ac(f);return n(...p)}});g.read=(m,n,p,r,u)=>{ac(f);m=m.node.Kd;if(u>=m.length)n=0;else{r=Math.min(m.length-
u,r);if(m.slice)for(var v=0;v<r;v++)n[p+v]=m[u+v];else for(v=0;v<r;v++)n[p+v]=m.get(u+v);n=r}return n};g.Cf=()=>{ac(f);z();throw new G(48);};f.Fe=g;return f}
var cc={},Ub,Ra=void 0,nc=(a,b)=>{dc=a;ec=b;if(fc)if(gc||=!0,0==a)hc=function(){var d=Math.max(0,ic+b-jc())|0;setTimeout(kc,d)};else if(1==a)hc=function(){lc(kc)};else if(2==a){if("undefined"==typeof mc)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);mc=function(d){c.push(d);postMessage("setimmediate","*")}}else mc=setImmediate;hc=function(){mc(kc)}}},jc;jc=()=>performance.now();
var uc=a=>{fc=a;var b=oc;gc=!1;kc=function(){if(!ka)if(0<pc.length){var c=pc.shift();c.Qg(c.Bg);if(qc){var d=qc,e=0==d%1?d-1:Math.floor(d);qc=c.Kg?e:(8*d+(e+.5))/9}h.setStatus&&(c=h.statusMessage||"Please wait...",d=qc,e=rc.Og,d?d<e?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(c):h.setStatus(""));b<oc||setTimeout(kc,0)}else b<oc||(sc=sc+1|0,1==dc&&1<ec&&0!=sc%ec?hc():(0==dc&&(ic=jc()),ka||h.preMainLoop&&!1===h.preMainLoop()||(tc(a),h.postMainLoop?.()),b<oc||("object"==
typeof SDL&&SDL.audio?.dh?.(),hc())))}},vc=a=>{a instanceof Na||"unwind"==a||da(1,a)},wc=0,xc=a=>{la=a;Pa||0<wc||(h.onExit?.(a),ka=!0);da(a,new Na(a))},yc=a=>{la=a;xc(a)},tc=a=>{if(!ka)try{if(a(),!(Pa||0<wc))try{la=a=la,xc(a)}catch(b){vc(b)}}catch(b){vc(b)}},zc=(a,b)=>setTimeout(()=>{tc(a)},b),gc=!1,hc=null,oc=0,fc=null,dc=0,ec=0,sc=0,pc=[];function Ac(){hc=null;oc++}function Bc(){oc++;var a=dc,b=ec,c=fc;fc=null;uc(c);nc(a,b);hc()}var rc={},ic,kc,qc,Cc=!1,Dc=!1,Ec=[];
function qb(){function a(){Dc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Fc){Fc=!0;ob.push({canHandle:function(c){return!h.$g&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:Gc(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Gc(d)}));var m=URL.createObjectURL(g),n=new Image;n.onload=()=>{var p=document.createElement("canvas");
p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);Hc[d]=p;URL.revokeObjectURL(m);e?.(c)};n.onerror=()=>{k(`Image ${m} could not be decoded`);f?.()};n.src=m}});ob.push({canHandle:function(c){return!h.Zg&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,m=URL.createObjectURL(new Blob([c],{type:Gc(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!g){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="",r=0,u=0,v=0;v<c.length;v++)for(r=r<<8|c[v],u+=8;6<=u;){var B=r>>u-6&63;u-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[B]}2==u?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&3)<<4],p+="=="):4==u&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&15)<<2],p+="=");n.src="data:audio/x-"+d.substr(-3)+";base64,"+p;f(n)}};n.src=m;zc(()=>{f(n)},1E4)}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!Dc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Ic=!1,Jc=void 0,Kc=void 0;function Lc(){if(!Cc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Mc=0;
function lc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Mc)Mc=b+1E3/60;else for(;b+2>=Mc;)Mc+=1E3/60;setTimeout(a,Math.max(Mc-b,0))}}function Gc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Nc=[];function Oc(){var a=h.canvas;Nc.forEach(b=>b(a.width,a.height))}
function Pc(a,b,c){b&&c?(a.zg=b,a.ng=c):(b=a.zg,c=a.ng);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Kc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var pb={},mc,Fc,L=12288,Qc=!1,Rc=0,Sc=0,Tc=0,M={alpha:!1,depth:!1,stencil:!1,antialias:!1},Uc={},Vc,Wc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Xc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Yc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Zc=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},$c=1,ad=[],N=[],bd=[],cd=[],dd=[],O=[],ed=[],fd=[],gd=[],hd={},jd=4,kd=0,ld=a=>{for(var b=$c++,c=a.length;c<b;c++)a[c]=null;return b},md=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=P[c](),g=f&&ld(d);f?(f.name=g,d[g]=f):Q||=1282;t[b+4*e>>2]=g}},od=(a,b)=>{a.Je||(a.Je=a.getContext,a.getContext=function(d,e){e=a.Je(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?nd(c,b):0},nd=(a,b)=>
{var c=ld(fd),d={handle:c,attributes:b,version:b.Tf,We:a};a.canvas&&(a.canvas.cf=d);fd[c]=d;("undefined"==typeof b.lg||b.lg)&&pd(d);return c},rd=a=>{qd=fd[a];h.Re=P=qd?.We},pd=a=>{a||=qd;if(!a.pg){a.pg=!0;var b=a.We;Wc(b);Xc(b);Yc(b);b.Te=b.getExtension("EXT_disjoint_timer_query");b.Xg=b.getExtension("WEBGL_multi_draw");Zc(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},sd={},Q,qd,td=a=>{var b=ab(a)+1,c=D(b);c&&E(a,q,c,b);return c},ud=[],vd=(a,b)=>{ud.length=
0;for(var c;c=q[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;ud.push(112==c?w[b>>2]:105==c?t[b>>2]:y[b>>3]);b+=d?8:4}return ud},wd=0,xd=[];function yd(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var n in g)if(g[n]!=m[n])return!1;return!0}for(var e in xd){var f=xd[e];if(f.Gf==a&&d(f.Jf,c))return}xd.push({Gf:a,Xf:b,Jf:c});xd.sort((g,m)=>g.Xf<m.Xf)}function zd(a){for(var b=0;b<xd.length;++b)xd[b].Gf==a&&(xd.splice(b,1),--b)}
function Ad(){return navigator.userActivation?navigator.userActivation.isActive:wd&&Bd.jf}function Cd(){if(Ad())for(var a=0;a<xd.length;++a){var b=xd[a];xd.splice(a,1);--a;b.Gf(...b.Jf)}}var Dd=[];function Ed(a){var b=Dd[a];b.target.removeEventListener(b.Ke,b.Nf,b.Oe);Dd.splice(a,1)}
function R(a){if(!a.target)return-4;if(a.Pe)a.Nf=function(c){++wd;Bd=a;Cd();a.Qe(c);Cd();--wd},a.target.addEventListener(a.Ke,a.Nf,a.Oe),Dd.push(a);else for(var b=0;b<Dd.length;++b)Dd[b].target==a.target&&Dd[b].Ke==a.Ke&&Ed(b--);return 0}function Fd(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}function Gd(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var Hd={},Bd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud={},Vd=[0,document,window],S=a=>{a=2<a?a?A(q,a):"":a;return Vd[a]||document.querySelector(a)},Xd=a=>{var b=ab(a)+1,c=Wd(b);E(a,q,c,b);return c},Yd=a=>{var b=T(),c=Wd(8),d=c+4;a=Xd(a.id);if(a=S(a))t[c>>2]=a.width,t[d>>2]=a.height;c=[t[c>>2],t[d>>2]];U(b);return c},Zd=(a,b,c)=>{a=S(a);if(!a)return-4;a.width=b;a.height=c;return 0},$d=(a,b,c)=>{if(a.Jg){var d=T();a=Xd(a.id);Zd(a,b,c);U(d)}else a.width=b,a.height=c},ae=a=>{function b(){document.fullscreenElement||
document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),$d(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=r,a.style.paddingTop=u,a.style.paddingBottom=v,a.style.marginLeft=B,a.style.marginRight=C,a.style.marginTop=F,a.style.marginBottom=W,document.body.style.margin=
cb,document.documentElement.style.overflow=bf,document.body.scroll=cf,a.style.Ze=df,a.cf&&a.cf.We.viewport(0,0,d,e),Ud.kf&&V(Ud.kf,37,0,Ud.Kf))}var c=Yd(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,r=a.style.paddingRight,u=a.style.paddingTop,v=a.style.paddingBottom,B=a.style.marginLeft,C=a.style.marginRight,F=a.style.marginTop,W=a.style.marginBottom,cb=document.body.style.margin,bf=document.documentElement.style.overflow,
cf=document.body.scroll,df=a.style.Ze;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},be=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},ce=a=>0>Vd.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},de=(a,b)=>{if(0!=b.Ff||0!=b.xf){ae(a);var c=b.wg?innerWidth:screen.width,d=b.wg?innerHeight:screen.height,e=ce(a),f=e.width;e=e.height;var g=Yd(a),m=g[0];g=g[1];3==b.Ff?(be(a,(d-e)/2,(c-f)/
2),c=f,d=e):2==b.Ff&&(c*g<m*d?(f=g*c/m,be(a,(d-f)/2,0),d=f):(f=m*d/g,be(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.mg&&(a.style.Ze="optimizeSpeed",a.style.Ze="-moz-crisp-edges",a.style.Ze="-o-crisp-edges",a.style.Ze="-webkit-optimize-contrast",a.style.Ze="optimize-contrast",a.style.Ze="crisp-edges",a.style.Ze="pixelated");f=2==b.xf?devicePixelRatio:
1;0!=b.xf&&(c=c*f|0,d=d*f|0,$d(a,c,d),a.cf&&a.cf.We.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Gd()?-3:-1;Ud=b;b.kf&&V(b.kf,37,0,b.Kf);return 0},ee=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},fe=(a,b)=>{y[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)y[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)y[a+
8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)l[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];l[a+1104]=b.connected;t[a+1108>>2]=b.index;t[a+8>>2]=b.axes.length;t[a+12>>2]=b.buttons.length;E(b.id,q,a+1112,64);E(b.mapping,q,a+1176,64)},ge=(a,b,c)=>{a=Ya(a);a=Hc[a];if(!a)return 0;var d=a.getContext("2d").getImageData(0,0,a.width,a.height),e=D(a.width*a.height*4);q.set(d.data,e);t[b>>2]=a.width;t[c>>2]=a.height;
return e},he=[],ie=(a,b,c,d,e,f,g,m)=>{b=N[b];if(a=P[a](b,c))d=m&&E(a.name,q,m,d),e&&(t[e>>2]=d),f&&(t[f>>2]=a.size),g&&(t[g>>2]=a.type)},je=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(Q||=1280);return;case 36345:d=0;break;case 34466:var e=P.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=P.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Q||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=
0;break;default:Q||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:t[b+4*a>>2]=e[a];break;case 2:x[b+4*a>>2]=e[a];break;case 4:l[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){Q||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:Q||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:c=d;w[b>>2]=c;w[b+4>>2]=(c-w[b>>2])/4294967296;break;case 0:t[b>>2]=d;break;case 2:x[b>>2]=d;break;case 4:l[b]=d?1:0}}else Q||=1281},ke=(a,b,c)=>{if(c){a=P.Te.getQueryObjectEXT(gd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d;w[c+4>>2]=(d-w[c>>2])/4294967296}else Q||=1281},le=(a,b,c)=>{if(c){a=P.Te.getQueryObjectEXT(gd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d}else Q||=1281};function me(){var a=Zc(P);return a=a.concat(a.map(b=>"GL_"+b))}
var ne=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),oe=a=>{var b=a.hf,c=a.cg,d;if(!b)for(a.hf=b={},a.bg={},d=0;d<P.getProgramParameter(a,35718);++d){var e=P.getActiveUniform(a,d);var f=e.name;e=e.size;var g=ne(f);g=0<g?f.slice(0,g):f;var m=a.Hf;a.Hf+=e;c[g]=[e,m];for(f=0;f<e;++f)b[m]=f,a.bg[m++]=g}},X=a=>{var b=P.gg;if(b){var c=b.hf[a];"number"==typeof c&&(b.hf[a]=c=P.getUniformLocation(b,b.bg[a]+(0<c?`[${c}]`:"")));return c}Q||=1282},pe=(a,b,c,d)=>{if(c)if(a=N[a],oe(a),a=P.getUniform(a,X(b)),"number"==
typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:x[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b]}else Q||=1281},qe=(a,b,c,d)=>{if(c)if(a=P.getVertexAttrib(a,b),34975==b)t[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:x[c>>2]=a;break;case 5:t[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b];break;case 5:t[c+
4*b>>2]=Math.fround(a[b])}else Q||=1281},re=(a,b,c,d,e)=>{a-=5120;a=1==a?q:4==a?t:6==a?x:5==a||28922==a?w:na;b=d*((kd||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+jd-1&-jd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},se=[],te=[],ue=(a,b)=>{if(!Gd())return-1;a=S(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Ad()?de(a,b):b.kg?(yd(de,1,[a,b]),1):-2:-3:-4},ve=()=>{try{if(navigator.getGamepads)return(Id=navigator.getGamepads())?
0:-1}catch(a){navigator.getGamepads=null}return-1},we=(a,b)=>{var c={target:S(2),Ke:"beforeunload",Pe:b,Qe:(d=event)=>{var e=V(b,28,0,a);e&&=e?A(q,e):"";if(e)return d.preventDefault(),d.returnValue=e},Oe:!0};return R(c)},xe=(a,b,c,d,e,f)=>{Jd||=D(256);a={target:S(a),Ke:f,Pe:d,Qe:(g=event)=>{var m=g.target.id?g.target.id:"",n=Jd;E(Fd(g.target),q,n+0,128);E(m,q,n+128,128);V(d,e,n,b)&&g.preventDefault()},Oe:c};return R(a)},ye=(a,b,c,d,e)=>{Ld||=D(276);return R({target:a,Ke:e,Pe:d,Qe:(f=event)=>{var g=
Ld,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;l[g]=n;l[g+1]=Gd();var p=n?m:Kd,r=p?.id||"";E(Fd(p),q,g+2,128);E(r,q,g+130,128);t[g+260>>2]=p?p.clientWidth:0;t[g+264>>2]=p?p.clientHeight:0;t[g+268>>2]=screen.width;t[g+272>>2]=screen.height;n&&(Kd=m);V(d,19,g,b)&&f.preventDefault()},Oe:c})},ze=(a,b,c,d,e)=>{Md||=D(1240);b={target:S(2),jf:!0,Ke:e,Pe:c,Qe:(f=event)=>{var g=Md;fe(g,f.gamepad);V(c,d,g,a)&&f.preventDefault()},
Oe:b};return R(b)},Ae=(a,b,c,d,e,f)=>{Nd||=D(160);a={target:S(a),Ke:f,Pe:d,Qe:g=>{var m=Nd;y[m>>3]=g.timeStamp;var n=m>>2;t[n+2]=g.location;l[n+12]=g.ctrlKey;l[n+13]=g.shiftKey;l[n+14]=g.altKey;l[n+15]=g.metaKey;l[n+16]=g.repeat;t[n+5]=g.charCode;t[n+6]=g.keyCode;t[n+7]=g.which;E(g.key||"",q,m+32,32);E(g.code||"",q,m+64,32);E(g.char||"",q,m+96,32);E(g.locale||"",q,m+128,32);V(d,e,m,b)&&g.preventDefault()},Oe:c};return R(a)},Be=(a,b,c)=>{y[a>>3]=b.timeStamp;a>>=2;t[a+2]=b.screenX;t[a+3]=b.screenY;
t[a+4]=b.clientX;t[a+5]=b.clientY;l[a+24]=b.ctrlKey;l[a+25]=b.shiftKey;l[a+26]=b.altKey;l[a+27]=b.metaKey;ma[2*a+14]=b.button;ma[2*a+15]=b.buttons;t[a+8]=b.movementX;t[a+9]=b.movementY;c=ce(c);t[a+10]=b.clientX-(c.left|0);t[a+11]=b.clientY-(c.top|0)},Ce=(a,b,c,d,e,f)=>{Od||=D(64);a=S(a);return R({target:a,jf:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Ke:f,Pe:d,Qe:(g=event)=>{Be(Od,g,a);V(d,e,Od,b)&&g.preventDefault()},Oe:c})},De=(a,b,c,d,e)=>{Pd||=D(257);return R({target:a,Ke:e,Pe:d,Qe:(f=event)=>
{var g=Pd,m=document.pointerLockElement||document.Je||document.dg||document.wf;l[g]=!!m;var n=m?.id||"";E(Fd(m),q,g+1,128);E(n,q,g+129,128);V(d,20,g,b)&&f.preventDefault()},Oe:c})},Ee=(a,b,c,d)=>{Qd||=D(36);a=S(a);return R({target:a,Ke:"resize",Pe:d,Qe:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=Qd;t[g>>2]=0;t[g+4>>2]=f.clientWidth;t[g+8>>2]=f.clientHeight;t[g+12>>2]=innerWidth;t[g+16>>2]=innerHeight;t[g+20>>2]=outerWidth;t[g+24>>2]=outerHeight;t[g+28>>2]=pageXOffset|0;t[g+32>>2]=
pageYOffset|0;V(d,10,g,b)&&e.preventDefault()}}},Oe:c})},Fe=(a,b,c,d,e,f)=>{Rd||=D(1552);a=S(a);return R({target:a,jf:"touchstart"==f||"touchend"==f,Ke:f,Pe:d,Qe:g=>{for(var m,n={},p=g.touches,r=0;r<p.length;++r)m=p[r],m.Qf=m.Wf=0,n[m.identifier]=m;for(r=0;r<g.changedTouches.length;++r)m=g.changedTouches[r],m.Qf=1,n[m.identifier]=m;for(r=0;r<g.targetTouches.length;++r)n[g.targetTouches[r].identifier].Wf=1;p=Rd;y[p>>3]=g.timeStamp;var u=p>>2;l[u+12]=g.ctrlKey;l[u+13]=g.shiftKey;l[u+14]=g.altKey;l[u+
15]=g.metaKey;u+=4;var v=ce(a),B=0;for(r in n)if(m=n[r],t[u]=m.identifier,t[u+1]=m.screenX,t[u+2]=m.screenY,t[u+3]=m.clientX,t[u+4]=m.clientY,t[u+5]=m.pageX,t[u+6]=m.pageY,l[u+28]=m.Qf,l[u+29]=m.Wf,t[u+8]=m.clientX-(v.left|0),t[u+9]=m.clientY-(v.top|0),u+=12,31<++B)break;t[p+8>>2]=B;V(d,e,p,b)&&g.preventDefault()},Oe:c})},Ge=(a,b,c)=>{var d=Vd[1];Sd||=D(8);return R({target:d,Ke:"visibilitychange",Pe:c,Qe:(e=event)=>{var f=Sd,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);
l[f]=document.hidden;t[f+4>>2]=g;V(c,21,f,a)&&e.preventDefault()},Oe:b})},He=(a,b,c,d)=>{Td||=D(96);return R({target:a,jf:!0,Ke:"wheel",Pe:d,Qe:(e=event)=>{var f=Td;Be(f,e,a);y[f+64>>3]=e.deltaX;y[f+72>>3]=e.deltaY;y[f+80>>3]=e.deltaZ;t[f+88>>2]=e.deltaMode;V(d,9,f,b)&&e.preventDefault()},Oe:c})},Ie={},Ke=()=>{if(!Je){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+
".UTF-8",_:ca||"./this.program"},b;for(b in Ie)void 0===Ie[b]?delete a[b]:a[b]=Ie[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Je=c}return Je},Je,Le=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Ja=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Le(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Ka=(a,b=[])=>{var c="vi".replace(/p/g,"i");(0,h["dynCall_"+c])(a,...b)},Me=a=>{try{a()}catch(b){z(b)}};
function Ne(){var a=Y,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...e)=>{Oe.push(c);try{return d(...e)}finally{ka||(Oe.pop(),Pe&&1===Qe&&0===Oe.length&&(Qe=0,Me(Re),"undefined"!=typeof Fibers&&Fibers.eh()))}}:d;return b}var Qe=0,Pe=null,Se=0,Oe=[],Te={},Ue={},Ve=0,We=null,Xe=[];function Ye(){var a=D(4108),b=a+12;w[a>>2]=b;w[a+4>>2]=b+4096;b=Oe[0];var c=Te[b];void 0===c&&(c=Ve++,Te[b]=c,Ue[c]=b);t[a+8>>2]=c;return a}
function Ze(a){if(!ka){if(0===Qe){var b=!1,c=!1;a((d=0)=>{if(!ka&&(Se=d,b=!0,c)){Qe=2;Me(()=>$e(Pe));"undefined"!=typeof pb&&fc&&Bc();d=!1;try{var e=(0,Y[Ue[t[Pe+8>>2]]])()}catch(m){e=m,d=!0}var f=!1;if(!Pe){var g=We;g&&(We=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(Qe=1,Pe=Ye(),"undefined"!=typeof pb&&fc&&Ac(),Me(()=>af(Pe)))}else 2===Qe?(Qe=0,Me(ef),ff(Pe),Pe=null,Xe.forEach(tc)):z(`invalid state: ${Qe}`);return Se}}
var Ia=0,Ga=(a,b)=>{b=1==b?Wd(a.length):D(a.length);a.subarray||a.slice||(a=new Uint8Array(a));q.set(a,b);return b};[44].forEach(a=>{lb[a]=new G(a);lb[a].stack="<generic error, no stack>"});zb=Array(4096);Nb(H,"/");J("/tmp");J("/home");J("/home/web_user");
(function(){J("/dev");eb(259,{read:()=>0,write:(d,e,f,g)=>g});Pb("/dev/null",259);db(1280,gb);db(1536,hb);Pb("/dev/tty",1280);Pb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Xa(a).byteLength);return a[--b]};K("/dev","random",c);K("/dev","urandom",c);J("/dev/shm");J("/dev/shm/tmp")})();
(function(){J("/proc");var a=J("/proc/self");J("/proc/self/fd");Nb({Ue(){var b=kb(a,"fd",16895,73);b.Ee={df(c,d){var e=Kb(+d);c={parent:null,Ue:{Uf:"fake"},Ee:{ff:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=Zb;h.FS_createDataFile=sb;h.FS_createPreloadedFile=tb;h.FS_unlink=Rb;h.FS_createLazyFile=bc;h.FS_createDevice=K;
h.requestFullscreen=function(a,b){function c(){Cc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Lc,Jc&&d.requestPointerLock(),Cc=!0,Kc?("undefined"!=typeof SDL&&(t[SDL.screen>>2]=w[SDL.screen>>2]|8388608),Pc(h.canvas),Oc()):Pc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Kc?("undefined"!=typeof SDL&&(t[SDL.screen>>2]=
w[SDL.screen>>2]&-8388609),Pc(h.canvas),Oc()):Pc(d));h.onFullScreen?.(Cc);h.onFullscreen?.(Cc)}Jc=a;Kc=b;"undefined"==typeof Jc&&(Jc=!0);"undefined"==typeof Kc&&(Kc=!1);var d=h.canvas;Ic||(Ic=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=lc;h.setCanvasSize=function(a,b,c){Pc(h.canvas,a,b);c||Oc()};h.pauseMainLoop=Ac;h.resumeMainLoop=Bc;
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=function(a,b,c,d){if(b&&h.Re&&a==h.canvas)return h.Re;var e;if(b){var f={antialias:!1,alpha:!1,Tf:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof sd&&(e=od(a,f)))var m=fd[e].We}else m=a.getContext("2d");if(!m)return null;c&&(h.Re=m,b&&rd(e),h.yg=b,Ec.forEach(n=>n()),qb());return m};for(var Hc={},P,Z=0;32>Z;++Z)he.push(Array(Z));
var gf=new Float32Array(288);for(Z=0;288>=Z;++Z)se[Z]=gf.subarray(0,Z);var hf=new Int32Array(288);for(Z=0;288>=Z;++Z)te[Z]=hf.subarray(0,Z);
var sf={O:function(a,b,c){Ra=c;try{var d=Kb(a);switch(b){case 0:var e=Qa();if(0>e)break;for(;xb[e];)e++;return Mb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Qa(),d.flags|=e,0;case 12:return e=Qa(),ma[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof cc||"ErrnoError"!==f.name)throw f;return-f.Xe}},cb:function(a,b,c){Ra=c;try{var d=Kb(a);switch(b){case 21509:return d.Ge?0:-59;case 21505:if(!d.Ge)return-59;if(d.Ge.Ve.rg){a=[3,28,127,21,4,0,1,0,17,
19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Qa();t[e>>2]=25856;t[e+4>>2]=5;t[e+8>>2]=191;t[e+12>>2]=35387;for(var f=0;32>f;f++)l[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.Ge?0:-59;case 21506:case 21507:case 21508:if(!d.Ge)return-59;if(d.Ge.Ve.sg)for(e=Qa(),a=[],f=0;32>f;f++)a.push(l[e+f+17]);return 0;case 21519:if(!d.Ge)return-59;e=Qa();return t[e>>2]=0;case 21520:return d.Ge?-28:-59;case 21531:e=Qa();if(!d.Fe.qg)throw new G(59);return d.Fe.qg(d,b,e);case 21523:if(!d.Ge)return-59;
d.Ge.Ve.tg&&(f=[24,80],e=Qa(),ma[e>>1]=f[0],ma[e+2>>1]=f[1]);return 0;case 21524:return d.Ge?0:-59;case 21515:return d.Ge?0:-59;default:return-28}}catch(g){if("undefined"==typeof cc||"ErrnoError"!==g.name)throw g;return-g.Xe}},db:function(a,b,c,d){Ra=d;try{b=b?A(q,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":Kb(a).path;if(0==e.length)throw new G(44);b=Ta(f+"/"+e)}var g=d?Qa():0;return Tb(b,c,g).fd}catch(m){if("undefined"==typeof cc||"ErrnoError"!==m.name)throw m;return-m.Xe}},Xa:()=>
{z("")},fb:()=>1,eb:(a,b,c)=>q.copyWithin(a,b,b+c),Wa:()=>{throw Infinity;},Oa:a=>{if(12448==a)return L=12288,1;L=12300;return 0},ac:(a,b,c,d,e)=>{if(62E3!=a)L=12296,c=0;else{if(b)for(;;){a=t[b>>2];if(12321==a)M.alpha=0<t[b+4>>2];else if(12325==a)M.depth=0<t[b+4>>2];else if(12326==a)M.stencil=0<t[b+4>>2];else if(12337==a)a=t[b+4>>2],M.antialias=0<a;else if(12338==a)a=t[b+4>>2],M.antialias=1==a;else if(12544==a)M.Ug=12547!=t[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(t[e>>2]=1),c&&0<d&&(w[c>>
2]=62002),L=12288,c=1):(L=12300,c=0)}return c},Fb:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;for(a=1;;){b=t[d>>2];if(12440==b)a=t[d+4>>2];else if(12344==b)break;else return L=12292,0;d+=8}if(2!=a)return L=12293,0;M.Tf=a-1;M.Vg=0;Vc=od(h.canvas,M);if(0!=Vc)return L=12288,rd(Vc),h.yg=!0,Ec.forEach(function(e){e()}),rd(null),62004;L=12297;return 0},jb:(a,b)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;L=12288;return 62006},ub:(a,b)=>{if(62E3!=a)return L=12296,0;if(62004!=b)return L=12294,
0;a=Vc;qd===fd[a]&&(qd=null);if("object"==typeof Hd)for(var c=fd[a].We.canvas,d=0;d<Dd.length;++d)Dd[d].target!=c||Ed(d--);fd[a]&&fd[a].We.canvas&&(fd[a].We.canvas.cf=void 0);fd[a]=null;L=12288;Rc==b&&(Rc=0);return 1},bb:(a,b)=>{if(62E3!=a)return L=12296,0;if(62006!=b)return L=12301,1;Sc==b&&(Sc=0);Tc==b&&(Tc=0);L=12288;return 1},Rb:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;if(!d)return L=12300,0;L=12288;switch(c){case 12320:return t[d>>2]=M.alpha?32:24,1;case 12321:return t[d>>
2]=M.alpha?8:0,1;case 12322:return t[d>>2]=8,1;case 12323:return t[d>>2]=8,1;case 12324:return t[d>>2]=8,1;case 12325:return t[d>>2]=M.depth?24:0,1;case 12326:return t[d>>2]=M.stencil?8:0,1;case 12327:return t[d>>2]=12344,1;case 12328:return t[d>>2]=62002,1;case 12329:return t[d>>2]=0,1;case 12330:return t[d>>2]=4096,1;case 12331:return t[d>>2]=16777216,1;case 12332:return t[d>>2]=4096,1;case 12333:return t[d>>2]=0,1;case 12334:return t[d>>2]=0,1;case 12335:return t[d>>2]=12344,1;case 12337:return t[d>>
2]=M.antialias?4:0,1;case 12338:return t[d>>2]=M.antialias?1:0,1;case 12339:return t[d>>2]=4,1;case 12340:return t[d>>2]=12344,1;case 12341:case 12342:case 12343:return t[d>>2]=-1,1;case 12345:case 12346:return t[d>>2]=0,1;case 12347:return t[d>>2]=0,1;case 12348:return t[d>>2]=1;case 12349:case 12350:return t[d>>2]=0,1;case 12351:return t[d>>2]=12430,1;case 12352:return t[d>>2]=4,1;case 12354:return t[d>>2]=0,1;default:return L=12292,0}},Q:a=>{L=12288;return 0!=a&&1!=a?0:62E3},La:()=>L,wc:(a,b,c)=>
{if(62E3!=a)return L=12296,0;b&&(t[b>>2]=1);c&&(t[c>>2]=4);Qc=!0;L=12288;return 1},Va:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;if(0!=d&&62004!=d)return L=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return L=12301,0;rd(d?Vc:null);Rc=d;Tc=b;Sc=c;L=12288;return 1},Ma:(a,b)=>{if(62E3!=a)return L=12296,0;L=12288;if(Uc[b])return Uc[b];switch(b){case 12371:a=td("Emscripten");break;case 12372:a=td("1.4 Emscripten EGL");break;case 12373:a=td("");break;case 12429:a=td("OpenGL_ES");break;default:return L=12300,
0}return Uc[b]=a},Sa:()=>{if(Qc)if(h.Re)if(h.Re.isContextLost())L=12302;else return L=12288,1;else L=12290;else L=12289;return 0},Ra:(a,b)=>{if(62E3!=a)return L=12296,0;0==b?nc(0,0):nc(1,b);L=12288;return 1},lc:a=>{if(62E3!=a)return L=12296,0;Tc=Sc=Rc=0;Qc=!1;L=12288;return 1},Pa:()=>{L=12288;return 1},Qa:()=>{L=12288;return 1},wa:(a,b,c)=>{b=vd(b,c);return Ma[a](...b)},c:(a,b,c)=>{b=vd(b,c);return Ma[a](...b)},y:(a,b,c)=>{b=vd(b,c);return Ma[a](...b)},Na:()=>{Ac();fc=null},P:()=>Date.now(),Fa:()=>
{if(!Gd())return-1;zd(de);var a=Vd[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Ja:()=>{zd(ee);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},Ia:a=>{Pa=!1;wc=0;la=a;xc(a)},g:()=>devicePixelRatio,e:(a,b,c)=>{a=S(a);if(!a)return-4;a=ce(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Dd:(a,b)=>{if(0>a||a>=Id.length)return-5;if(!Id[a])return-7;fe(b,
Id[a]);return 0},m:jc,aa:()=>Id.length,Ed:(a,b,c)=>ge(a?A(q,a):"",b,c),Gb:(a,b,c)=>{a=jf(a);return(a=xb[a])?ge(a.path,b,c):0},Ka:(a,b)=>{t[a>>2]=screen.width;t[b>>2]=screen.height},ja:a=>P.activeTexture(a),ia:(a,b)=>{P.attachShader(N[a],O[b])},Ba:(a,b)=>{P.Te.beginQueryEXT(a,gd[b])},ha:(a,b,c)=>{P.bindAttribLocation(N[a],b,c?A(q,c):"")},ga:(a,b)=>{P.bindBuffer(a,ad[b])},fa:(a,b)=>{P.bindFramebuffer(a,bd[b])},ea:(a,b)=>{P.bindRenderbuffer(a,cd[b])},da:(a,b)=>{P.bindTexture(a,dd[b])},sa:a=>{P.bindVertexArray(ed[a])},
ca:(a,b,c,d)=>P.blendColor(a,b,c,d),ba:a=>P.blendEquation(a),$:(a,b)=>P.blendEquationSeparate(a,b),_:(a,b)=>P.blendFunc(a,b),Z:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),Y:(a,b,c,d)=>{P.bufferData(a,c?q.subarray(c,c+b):b,d)},X:(a,b,c,d)=>{P.bufferSubData(a,b,q.subarray(d,d+c))},W:a=>P.checkFramebufferStatus(a),V:a=>P.clear(a),U:(a,b,c,d)=>P.clearColor(a,b,c,d),T:a=>P.clearDepth(a),S:a=>P.clearStencil(a),Cd:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},Bd:a=>{P.compileShader(O[a])},Ad:(a,b,c,d,e,f,g,m)=>
{P.compressedTexImage2D(a,b,c,d,e,f,m?q.subarray(m,m+g):null)},zd:(a,b,c,d,e,f,g,m,n)=>{P.compressedTexSubImage2D(a,b,c,d,e,f,g,n?q.subarray(n,n+m):null)},yd:(a,b,c,d,e,f,g,m)=>P.copyTexImage2D(a,b,c,d,e,f,g,m),xd:(a,b,c,d,e,f,g,m)=>P.copyTexSubImage2D(a,b,c,d,e,f,g,m),wd:()=>{var a=ld(N),b=P.createProgram();b.name=a;b.pf=b.mf=b.nf=0;b.Hf=1;N[a]=b;return a},vd:a=>{var b=ld(O);O[b]=P.createShader(a);return b},ud:a=>P.cullFace(a),td:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=ad[d];e&&(P.deleteBuffer(e),
e.name=0,ad[d]=null)}},sd:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=bd[d];e&&(P.deleteFramebuffer(e),e.name=0,bd[d]=null)}},rd:a=>{if(a){var b=N[a];b?(P.deleteProgram(b),b.name=0,N[a]=null):Q||=1281}},Da:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=gd[d];e&&(P.Te.deleteQueryEXT(e),gd[d]=null)}},qd:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=cd[d];e&&(P.deleteRenderbuffer(e),e.name=0,cd[d]=null)}},pd:a=>{if(a){var b=O[a];b?(P.deleteShader(b),O[a]=null):Q||=1281}},od:(a,b)=>{for(var c=
0;c<a;c++){var d=t[b+4*c>>2],e=dd[d];e&&(P.deleteTexture(e),e.name=0,dd[d]=null)}},ra:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];P.deleteVertexArray(ed[d]);ed[d]=null}},nd:a=>P.depthFunc(a),md:a=>{P.depthMask(!!a)},ld:(a,b)=>P.depthRange(a,b),kd:(a,b)=>{P.detachShader(N[a],O[b])},jd:a=>P.disable(a),id:a=>{P.disableVertexAttribArray(a)},hd:(a,b,c)=>{P.drawArrays(a,b,c)},na:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},oa:(a,b)=>{for(var c=he[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];P.drawBuffers(c)},gd:(a,
b,c,d)=>{P.drawElements(a,b,c,d)},ma:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},fd:a=>P.enable(a),ed:a=>{P.enableVertexAttribArray(a)},Aa:a=>{P.Te.endQueryEXT(a)},dd:()=>P.finish(),cd:()=>P.flush(),bd:(a,b,c,d)=>{P.framebufferRenderbuffer(a,b,c,cd[d])},ad:(a,b,c,d,e)=>{P.framebufferTexture2D(a,b,c,dd[d],e)},$c:a=>P.frontFace(a),_c:(a,b)=>{md(a,b,"createBuffer",ad)},Yc:(a,b)=>{md(a,b,"createFramebuffer",bd)},Ea:(a,b)=>{for(var c=0;c<a;c++){var d=P.Te.createQueryEXT();if(!d){for(Q||=1282;c<a;)t[b+
4*c++>>2]=0;break}var e=ld(gd);d.name=e;gd[e]=d;t[b+4*c>>2]=e}},Xc:(a,b)=>{md(a,b,"createRenderbuffer",cd)},Wc:(a,b)=>{md(a,b,"createTexture",dd)},qa:(a,b)=>{md(a,b,"createVertexArray",ed)},Zc:a=>P.generateMipmap(a),Vc:(a,b,c,d,e,f,g)=>{ie("getActiveAttrib",a,b,c,d,e,f,g)},Uc:(a,b,c,d,e,f,g)=>{ie("getActiveUniform",a,b,c,d,e,f,g)},Tc:(a,b,c,d)=>{a=P.getAttachedShaders(N[a]);var e=a.length;e>b&&(e=b);t[c>>2]=e;for(b=0;b<e;++b)t[d+4*b>>2]=O.indexOf(a[b])},Sc:(a,b)=>P.getAttribLocation(N[a],b?A(q,b):
""),Rc:(a,b)=>je(a,b,4),Qc:(a,b,c)=>{c?t[c>>2]=P.getBufferParameter(a,b):Q||=1281},Pc:()=>{var a=P.getError()||Q;Q=0;return a},Oc:(a,b)=>je(a,b,2),Nc:(a,b,c,d)=>{a=P.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;t[d>>2]=a},Mc:(a,b)=>je(a,b,0),Kc:(a,b,c,d)=>{a=P.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,q,d,b):0;c&&(t[c>>2]=b)},Lc:(a,b,c)=>{if(c)if(a>=$c)Q||=1281;else if(a=N[a],35716==b)a=P.getProgramInfoLog(a),
null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b){if(!a.pf)for(b=0;b<P.getProgramParameter(a,35718);++b)a.pf=Math.max(a.pf,P.getActiveUniform(a,b).name.length+1);t[c>>2]=a.pf}else if(35722==b){if(!a.mf)for(b=0;b<P.getProgramParameter(a,35721);++b)a.mf=Math.max(a.mf,P.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.mf}else if(35381==b){if(!a.nf)for(b=0;b<P.getProgramParameter(a,35382);++b)a.nf=Math.max(a.nf,P.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.nf}else t[c>>2]=P.getProgramParameter(a,
b);else Q||=1281},ua:ke,xa:le,ta:ke,va:le,ya:(a,b,c)=>{c?t[c>>2]=P.Te.getQueryEXT(a,b):Q||=1281},Jc:(a,b,c)=>{c?t[c>>2]=P.getRenderbufferParameter(a,b):Q||=1281},Hc:(a,b,c,d)=>{a=P.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,q,d,b):0;c&&(t[c>>2]=b)},Gc:(a,b,c,d)=>{a=P.getShaderPrecisionFormat(a,b);t[c>>2]=a.rangeMin;t[c+4>>2]=a.rangeMax;t[d>>2]=a.precision},Fc:(a,b,c,d)=>{if(a=P.getShaderSource(O[a]))b=0<b&&d?E(a,q,d,b):0,c&&(t[c>>2]=b)},Ic:(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(O[a]),
null===a&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(O[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=P.getShaderParameter(O[a],b):Q||=1281},Ec:a=>{var b=hd[a];if(!b){switch(a){case 7939:b=td(me().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=P.getParameter(a))||(Q||=1280);b=b?td(b):0;break;case 7938:b=td(`OpenGL ES 2.0 (${P.getParameter(7938)})`);break;case 35724:b=P.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&
(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=td(b);break;default:Q||=1280}hd[a]=b}return b},Dc:(a,b,c)=>{c?x[c>>2]=P.getTexParameter(a,b):Q||=1281},Cc:(a,b,c)=>{c?t[c>>2]=P.getTexParameter(a,b):Q||=1281},zc:(a,b)=>{b=b?A(q,b):"";if(a=N[a]){oe(a);var c=a.hf,d=0,e=b,f=ne(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.cg[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else Q||=1281;return-1},Bc:(a,b,c)=>{pe(a,b,c,2)},Ac:(a,b,c)=>{pe(a,b,c,0)},
vc:(a,b,c)=>{c?t[c>>2]=P.getVertexAttribOffset(a,b):Q||=1281},yc:(a,b,c)=>{qe(a,b,c,2)},xc:(a,b,c)=>{qe(a,b,c,5)},uc:(a,b)=>P.hint(a,b),tc:a=>(a=ad[a])?P.isBuffer(a):0,sc:a=>P.isEnabled(a),rc:a=>(a=bd[a])?P.isFramebuffer(a):0,qc:a=>(a=N[a])?P.isProgram(a):0,Ca:a=>(a=gd[a])?P.Te.isQueryEXT(a):0,pc:a=>(a=cd[a])?P.isRenderbuffer(a):0,oc:a=>(a=O[a])?P.isShader(a):0,nc:a=>(a=dd[a])?P.isTexture(a):0,pa:a=>(a=ed[a])?P.isVertexArray(a):0,mc:a=>P.lineWidth(a),kc:a=>{a=N[a];P.linkProgram(a);a.hf=0;a.cg={}},
jc:(a,b)=>{3317==a?jd=b:3314==a&&(kd=b);P.pixelStorei(a,b)},ic:(a,b)=>P.polygonOffset(a,b),za:(a,b)=>{P.Te.queryCounterEXT(gd[a],b)},hc:(a,b,c,d,e,f,g)=>{(g=re(f,e,c,d,g))?P.readPixels(a,b,c,d,e,f,g):Q||=1280},gc:()=>{},fc:(a,b,c,d)=>P.renderbufferStorage(a,b,c,d),ec:(a,b)=>{P.sampleCoverage(a,!!b)},dc:(a,b,c,d)=>P.scissor(a,b,c,d),cc:()=>{Q||=1280},bc:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=w[c+4*f>>2])?A(q,g,d?w[d+4*f>>2]:void 0):"";e+=g}P.shaderSource(O[a],e)},$b:(a,b,c)=>P.stencilFunc(a,
b,c),_b:(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),Zb:a=>P.stencilMask(a),Yb:(a,b)=>P.stencilMaskSeparate(a,b),Xb:(a,b,c)=>P.stencilOp(a,b,c),Wb:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),Vb:(a,b,c,d,e,f,g,m,n)=>{n=n?re(m,g,d,e,n):null;P.texImage2D(a,b,c,d,e,f,g,m,n)},Ub:(a,b,c)=>P.texParameterf(a,b,c),Tb:(a,b,c)=>{P.texParameterf(a,b,x[c>>2])},Sb:(a,b,c)=>P.texParameteri(a,b,c),Qb:(a,b,c)=>{P.texParameteri(a,b,t[c>>2])},Pb:(a,b,c,d,e,f,g,m,n)=>{n=n?re(m,g,e,f,n):null;P.texSubImage2D(a,b,c,d,e,f,g,m,
n)},Ob:(a,b)=>{P.uniform1f(X(a),b)},Nb:(a,b,c)=>{if(288>=b)for(var d=se[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);P.uniform1fv(X(a),d)},Mb:(a,b)=>{P.uniform1i(X(a),b)},Lb:(a,b,c)=>{if(288>=b)for(var d=te[b],e=0;e<b;++e)d[e]=t[c+4*e>>2];else d=t.subarray(c>>2,c+4*b>>2);P.uniform1iv(X(a),d)},Kb:(a,b,c)=>{P.uniform2f(X(a),b,c)},Jb:(a,b,c)=>{if(144>=b)for(var d=se[2*b],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);P.uniform2fv(X(a),d)},
Ib:(a,b,c)=>{P.uniform2i(X(a),b,c)},Hb:(a,b,c)=>{if(144>=b)for(var d=te[2*b],e=0;e<2*b;e+=2)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2];else d=t.subarray(c>>2,c+8*b>>2);P.uniform2iv(X(a),d)},Eb:(a,b,c,d)=>{P.uniform3f(X(a),b,c,d)},Db:(a,b,c)=>{if(96>=b)for(var d=se[3*b],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);P.uniform3fv(X(a),d)},Cb:(a,b,c,d)=>{P.uniform3i(X(a),b,c,d)},Bb:(a,b,c)=>{if(96>=b)for(var d=te[3*b],e=0;e<3*b;e+=3)d[e]=
t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2];else d=t.subarray(c>>2,c+12*b>>2);P.uniform3iv(X(a),d)},Ab:(a,b,c,d,e)=>{P.uniform4f(X(a),b,c,d,e)},zb:(a,b,c)=>{if(72>=b){var d=se[4*b],e=x;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);P.uniform4fv(X(a),d)},yb:(a,b,c,d,e)=>{P.uniform4i(X(a),b,c,d,e)},xb:(a,b,c)=>{if(72>=b)for(var d=te[4*b],e=0;e<4*b;e+=4)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*
e+8)>>2],d[e+3]=t[c+(4*e+12)>>2];else d=t.subarray(c>>2,c+16*b>>2);P.uniform4iv(X(a),d)},wb:(a,b,c,d)=>{if(72>=b)for(var e=se[4*b],f=0;f<4*b;f+=4)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2];else e=x.subarray(d>>2,d+16*b>>2);P.uniformMatrix2fv(X(a),!!c,e)},vb:(a,b,c,d)=>{if(32>=b)for(var e=se[9*b],f=0;f<9*b;f+=9)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2],e[f+4]=x[d+(4*f+16)>>2],e[f+5]=x[d+(4*f+20)>>2],e[f+6]=x[d+
(4*f+24)>>2],e[f+7]=x[d+(4*f+28)>>2],e[f+8]=x[d+(4*f+32)>>2];else e=x.subarray(d>>2,d+36*b>>2);P.uniformMatrix3fv(X(a),!!c,e)},tb:(a,b,c,d)=>{if(18>=b){var e=se[16*b],f=x;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=x.subarray(d>>2,d+64*b>>2);P.uniformMatrix4fv(X(a),
!!c,e)},sb:a=>{a=N[a];P.useProgram(a);P.gg=a},rb:a=>{P.validateProgram(N[a])},qb:(a,b)=>P.vertexAttrib1f(a,b),pb:(a,b)=>{P.vertexAttrib1f(a,x[b>>2])},ob:(a,b,c)=>P.vertexAttrib2f(a,b,c),nb:(a,b)=>{P.vertexAttrib2f(a,x[b>>2],x[b+4>>2])},mb:(a,b,c,d)=>P.vertexAttrib3f(a,b,c,d),lb:(a,b)=>{P.vertexAttrib3f(a,x[b>>2],x[b+4>>2],x[b+8>>2])},kb:(a,b,c,d,e)=>P.vertexAttrib4f(a,b,c,d,e),ib:(a,b)=>{P.vertexAttrib4f(a,x[b>>2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},ka:(a,b)=>{P.vertexAttribDivisor(a,b)},hb:(a,b,c,d,
e,f)=>{P.vertexAttribPointer(a,b,c,!!d,e,f)},gb:(a,b,c,d)=>P.viewport(a,b,c,d),o:()=>1,Ga:(a,b,c)=>ue(a,{Ff:t[c>>2],xf:t[c+4>>2],mg:t[c+8>>2],kg:b,kf:t[c+12>>2],Kf:t[c+16>>2]}),K:(a,b)=>{a=S(a);return a?a.requestPointerLock?Ad()?ee(a):b?(yd(ee,2,[a]),1):-2:-1:-4},Ya:()=>{z("OOM")},la:ve,p:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:we(a,b),C:(a,b,c,d)=>xe(a,b,c,d,12,"blur"),f:Zd,l:(a,b,c)=>{a=S(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},D:(a,b,c,d)=>xe(a,b,
c,d,13,"focus"),s:(a,b,c,d)=>{if(!Gd())return-1;a=S(a);if(!a)return-4;ye(a,b,c,d,"webkitfullscreenchange");return ye(a,b,c,d,"fullscreenchange")},k:(a,b,c)=>ve()?-1:ze(a,b,c,26,"gamepadconnected"),j:(a,b,c)=>ve()?-1:ze(a,b,c,27,"gamepaddisconnected"),v:(a,b,c,d)=>Ae(a,b,c,d,2,"keydown"),t:(a,b,c,d)=>Ae(a,b,c,d,1,"keypress"),u:(a,b,c,d)=>Ae(a,b,c,d,3,"keyup"),I:(a,b,c,d)=>Ce(a,b,c,d,5,"mousedown"),G:(a,b,c,d)=>Ce(a,b,c,d,33,"mouseenter"),F:(a,b,c,d)=>Ce(a,b,c,d,34,"mouseleave"),J:(a,b,c,d)=>Ce(a,b,
c,d,8,"mousemove"),H:(a,b,c,d)=>Ce(a,b,c,d,6,"mouseup"),w:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Je||document.body.dg||document.body.wf))return-1;a=S(a);if(!a)return-4;De(a,b,c,d,"mozpointerlockchange");De(a,b,c,d,"webkitpointerlockchange");De(a,b,c,d,"mspointerlockchange");return De(a,b,c,d,"pointerlockchange")},r:(a,b,c,d)=>Ee(a,b,c,d),x:(a,b,c,d)=>Fe(a,b,c,d,25,"touchcancel"),A:(a,b,c,d)=>Fe(a,b,c,d,23,"touchend"),z:(a,b,c,d)=>Fe(a,b,c,d,24,
"touchmove"),B:(a,b,c,d)=>Fe(a,b,c,d,22,"touchstart"),q:(a,b,c)=>Ge(a,b,c),E:(a,b,c,d)=>(a=S(a))?"undefined"!=typeof a.onwheel?He(a,b,c,d):-1:-4,Ha:a=>document.title=a?A(q,a):"",n:a=>Ze(b=>zc(b,a)),Za:(a,b)=>{var c=0;Ke().forEach((d,e)=>{var f=b+c;e=w[a+4*e>>2]=f;for(f=0;f<d.length;++f)l[e++]=d.charCodeAt(f);l[e]=0;c+=d.length+1});return 0},_a:(a,b)=>{var c=Ke();w[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);w[b>>2]=d;return 0},R:yc,N:function(a){try{var b=Kb(a);Vb(b);return 0}catch(c){if("undefined"==
typeof cc||"ErrnoError"!==c.name)throw c;return c.Xe}},ab:function(a,b,c,d){try{a:{var e=Kb(a);a=b;for(var f,g=b=0;g<c;g++){var m=w[a>>2],n=w[a+4>>2];a+=8;var p=e,r=f,u=l;if(0>n||0>r)throw new G(28);if(null===p.fd)throw new G(8);if(1===(p.flags&2097155))throw new G(8);if(I(p.node.mode))throw new G(31);if(!p.Fe.read)throw new G(28);var v="undefined"!=typeof r;if(!v)r=p.position;else if(!p.seekable)throw new G(70);var B=p.Fe.read(p,u,m,n,r);v||(p.position+=B);var C=B;if(0>C){var F=-1;break a}b+=C;if(C<
n)break;"undefined"!=typeof f&&(f+=C)}F=b}w[d>>2]=F;return 0}catch(W){if("undefined"==typeof cc||"ErrnoError"!==W.name)throw W;return W.Xe}},Ua:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=Kb(a);Wb(f,b,d);Fa=[f.position>>>0,(Ea=f.position,1<=+Math.abs(Ea)?0<Ea?+Math.floor(Ea/4294967296)>>>0:~~+Math.ceil((Ea-+(~~Ea>>>0))/4294967296)>>>0:0)];t[e>>2]=Fa[0];t[e+4>>2]=Fa[1];f.Bf&&0===b&&0===d&&(f.Bf=null);return 0}catch(g){if("undefined"==typeof cc||
"ErrnoError"!==g.name)throw g;return g.Xe}},$a:function(a,b,c,d){try{a:{var e=Kb(a);a=b;for(var f,g=b=0;g<c;g++){var m=w[a>>2],n=w[a+4>>2];a+=8;var p=Xb(e,l,m,n,f);if(0>p){var r=-1;break a}b+=p;"undefined"!=typeof f&&(f+=p)}r=b}w[d>>2]=r;return 0}catch(u){if("undefined"==typeof cc||"ErrnoError"!==u.name)throw u;return u.Xe}},i:kf,b:lf,h:mf,M:nf,Ta:of,a:pf,d:qf,L:rf},Y=function(){function a(c){Y=c.exports;Y=Ne();ja=Y.Fd;c=ja.buffer;h.HEAP8=l=new Int8Array(c);h.HEAP16=ma=new Int16Array(c);h.HEAPU8=
q=new Uint8Array(c);h.HEAPU16=na=new Uint16Array(c);h.HEAP32=t=new Int32Array(c);h.HEAPU32=w=new Uint32Array(c);h.HEAPF32=x=new Float32Array(c);h.HEAPF64=y=new Float64Array(c);pa.unshift(Y.Gd);xa("wasm-instantiate");return Y}var b={a:sf};wa("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return k(`Module.instantiateWasm callback failed with error: ${c}`),!1}za||=ya("index.wasm")?"index.wasm":h.locateFile?h.locateFile("index.wasm",ea):ea+"index.wasm";Da(b,function(c){a(c.instance)});
return{}}(),tf=h._main=(a,b)=>(tf=h._main=Y.Hd)(a,b),ff=a=>(ff=Y.Id)(a),D=a=>(D=Y.Jd)(a),jf=a=>(jf=Y.Ld)(a),uf=(a,b)=>(uf=Y.Md)(a,b),U=a=>(U=Y.Nd)(a),Wd=a=>(Wd=Y.Od)(a),T=()=>(T=Y.Pd)();h.dynCall_viii=(a,b,c,d)=>(h.dynCall_viii=Y.Qd)(a,b,c,d);
var dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=h.dynCall_vi=Y.Rd)(a,b),vf=h.dynCall_viiii=(a,b,c,d,e)=>(vf=h.dynCall_viiii=Y.Sd)(a,b,c,d,e),dynCall_iii=h.dynCall_iii=(a,b,c)=>(dynCall_iii=h.dynCall_iii=Y.Td)(a,b,c),dynCall_v=h.dynCall_v=a=>(dynCall_v=h.dynCall_v=Y.Ud)(a),wf=h.dynCall_ii=(a,b)=>(wf=h.dynCall_ii=Y.Vd)(a,b),V=h.dynCall_iiii=(a,b,c,d)=>(V=h.dynCall_iiii=Y.Wd)(a,b,c,d),xf=h.dynCall_iiiii=(a,b,c,d,e)=>(xf=h.dynCall_iiiii=Y.Xd)(a,b,c,d,e),yf=h.dynCall_jiji=(a,b,c,d,e)=>(yf=h.dynCall_jiji=
Y.Yd)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=Y.Zd)(a,b);h.dynCall_iiiiii=(a,b,c,d,e,f)=>(h.dynCall_iiiiii=Y._d)(a,b,c,d,e,f);h.dynCall_viiiii=(a,b,c,d,e,f)=>(h.dynCall_viiiii=Y.$d)(a,b,c,d,e,f);var dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=Y.ae)(a,b,c);h.dynCall_viiiiiii=(a,b,c,d,e,f,g,m)=>(h.dynCall_viiiiiii=Y.be)(a,b,c,d,e,f,g,m);var zf=h.dynCall_iiiiiii=(a,b,c,d,e,f,g)=>(zf=h.dynCall_iiiiiii=Y.ce)(a,b,c,d,e,f,g);
h.dynCall_iiiiiiii=(a,b,c,d,e,f,g,m)=>(h.dynCall_iiiiiiii=Y.de)(a,b,c,d,e,f,g,m);h.dynCall_iiiiiiiiii=(a,b,c,d,e,f,g,m,n,p)=>(h.dynCall_iiiiiiiiii=Y.ee)(a,b,c,d,e,f,g,m,n,p);h.dynCall_iiiiiiiiiiiiiiff=(a,b,c,d,e,f,g,m,n,p,r,u,v,B,C,F)=>(h.dynCall_iiiiiiiiiiiiiiff=Y.fe)(a,b,c,d,e,f,g,m,n,p,r,u,v,B,C,F);h.dynCall_iiiiiidiiff=(a,b,c,d,e,f,g,m,n,p,r)=>(h.dynCall_iiiiiidiiff=Y.ge)(a,b,c,d,e,f,g,m,n,p,r);h.dynCall_iiiiiiiii=(a,b,c,d,e,f,g,m,n)=>(h.dynCall_iiiiiiiii=Y.he)(a,b,c,d,e,f,g,m,n);
h.dynCall_viiiiiiiiiii=(a,b,c,d,e,f,g,m,n,p,r,u)=>(h.dynCall_viiiiiiiiiii=Y.ie)(a,b,c,d,e,f,g,m,n,p,r,u);h.dynCall_i=a=>(h.dynCall_i=Y.je)(a);h.dynCall_vffff=(a,b,c,d,e)=>(h.dynCall_vffff=Y.ke)(a,b,c,d,e);h.dynCall_vf=(a,b)=>(h.dynCall_vf=Y.le)(a,b);h.dynCall_viiiiiiii=(a,b,c,d,e,f,g,m,n)=>(h.dynCall_viiiiiiii=Y.me)(a,b,c,d,e,f,g,m,n);h.dynCall_viiiiiiiii=(a,b,c,d,e,f,g,m,n,p)=>(h.dynCall_viiiiiiiii=Y.ne)(a,b,c,d,e,f,g,m,n,p);h.dynCall_vff=(a,b,c)=>(h.dynCall_vff=Y.oe)(a,b,c);
h.dynCall_vfi=(a,b,c)=>(h.dynCall_vfi=Y.pe)(a,b,c);h.dynCall_viif=(a,b,c,d)=>(h.dynCall_viif=Y.qe)(a,b,c,d);h.dynCall_vif=(a,b,c)=>(h.dynCall_vif=Y.re)(a,b,c);h.dynCall_viff=(a,b,c,d)=>(h.dynCall_viff=Y.se)(a,b,c,d);h.dynCall_vifff=(a,b,c,d,e)=>(h.dynCall_vifff=Y.te)(a,b,c,d,e);h.dynCall_viffff=(a,b,c,d,e,f)=>(h.dynCall_viffff=Y.ue)(a,b,c,d,e,f);h.dynCall_viiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_viiiiii=Y.ve)(a,b,c,d,e,f,g);h.dynCall_iidiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iidiiii=Y.we)(a,b,c,d,e,f,g);
h.dynCall_iid=(a,b,c)=>(h.dynCall_iid=Y.xe)(a,b,c);h.dynCall_di=(a,b)=>(h.dynCall_di=Y.ye)(a,b);h.dynCall_fi=(a,b)=>(h.dynCall_fi=Y.ze)(a,b);var af=a=>(af=Y.Ae)(a),Re=()=>(Re=Y.Be)(),$e=a=>($e=Y.Ce)(a),ef=()=>(ef=Y.De)();function pf(a,b){var c=T();try{dynCall_vi(a,b)}catch(d){U(c);if(d!==d+0)throw d;uf(1,0)}}function qf(a,b,c){var d=T();try{dynCall_vii(a,b,c)}catch(e){U(d);if(e!==e+0)throw e;uf(1,0)}}function lf(a,b,c,d){var e=T();try{return V(a,b,c,d)}catch(f){U(e);if(f!==f+0)throw f;uf(1,0)}}
function kf(a,b){var c=T();try{return wf(a,b)}catch(d){U(c);if(d!==d+0)throw d;uf(1,0)}}function mf(a,b,c,d,e){var f=T();try{return xf(a,b,c,d,e)}catch(g){U(f);if(g!==g+0)throw g;uf(1,0)}}function nf(a,b,c,d,e,f,g){var m=T();try{return zf(a,b,c,d,e,f,g)}catch(n){U(m);if(n!==n+0)throw n;uf(1,0)}}function rf(a,b,c,d,e){var f=T();try{vf(a,b,c,d,e)}catch(g){U(f);if(g!==g+0)throw g;uf(1,0)}}function of(a,b,c,d,e){var f=T();try{return yf(a,b,c,d,e)}catch(g){U(f);if(g!==g+0)throw g;uf(1,0)}}
h.addRunDependency=wa;h.removeRunDependency=xa;h.FS_createPreloadedFile=tb;h.FS_unlink=a=>Rb(a);h.FS_createPath=Zb;h.FS_createDevice=K;h.FS_createDataFile=(a,b,c,d,e,f)=>{sb(a,b,c,d,e,f)};h.FS_createLazyFile=bc;h.allocate=Ga;var Af;va=function Bf(){Af||Cf();Af||(va=Bf)};function Df(a=[]){var b=tf;a.unshift(ca);var c=a.length,d=Wd(4*(c+1)),e=d;a.forEach(g=>{w[e>>2]=Xd(g);e+=4});w[e>>2]=0;try{var f=b(c,d);yc(f,!0)}catch(g){vc(g)}}
function Cf(){var a=ba;function b(){if(!Af&&(Af=!0,h.calledRun=!0,!ka)){h.noFSInit||Yb||(Yb=!0,h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?K("/dev","stdin",h.stdin):Qb("/dev/tty","/dev/stdin"),h.stdout?K("/dev","stdout",null,h.stdout):Qb("/dev/tty","/dev/stdout"),h.stderr?K("/dev","stderr",null,h.stderr):Qb("/dev/tty1","/dev/stderr"),Tb("/dev/stdin",0),Tb("/dev/stdout",1),Tb("/dev/stderr",1));Ab=!1;Oa(pa);Oa(qa);h.onRuntimeInitialized?.();Ef&&Df(a);if(h.postRun)for("function"==typeof h.postRun&&
(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ra.unshift(c)}Oa(ra)}}if(!(0<ta)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)sa();Oa(oa);0<ta||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Ef=!0;h.noInitialRun&&(Ef=!1);Cf();
