var h;h||=typeof Module != 'undefined' ? Module : {};let aa;(aa=h).expectedDataFileDownloads??(aa.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;"undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a||function(b){function c(p,u,v){let z;(z=h).dataFileDownloads??(z.dataFileDownloads={});fetch(p).catch(B=>Promise.reject(Error(`Network Error: ${p}`,{cause:B}))).then(B=>{if(!B.ok)return Promise.reject(Error(`${B.status}: ${B.url}`));if(!B.body&&B.arrayBuffer)return B.arrayBuffer().then(v);const F=B.body.getReader(),H=()=>F.read().then(Fb).catch(X=>
Promise.reject(Error(`Unexpected error while handling : ${B.url} ${X}`,{cause:X}))),Y=[],Gb=Number(B.headers.get("Content-Length")??u);let ab=0;const Fb=({done:X,value:Cc})=>{if(X){var Ea=new Uint8Array(Y.map(Hb=>Hb.length).reduce((Hb,Ae)=>Hb+Ae,0));X=0;for(var Fa of Y)Ea.set(Fa,X),X+=Fa.length;v(Ea.buffer)}else{Y.push(Cc);ab+=Cc.length;h.dataFileDownloads[p]={loaded:ab,total:Gb};X=Fa=0;for(Ea of Object.values(h.dataFileDownloads))Fa+=Ea.loaded,X+=Ea.total;h.setStatus?.(`Downloading data... (${Fa}/${X})`);
return H()}};h.setStatus?.("Downloading data...");return H()})}function d(p){console.error("package error:",p)}function e(p){function u(F,H,Y){this.start=F;this.end=H;this.audio=Y}function v(F){if(!F)throw"Loading data file failed."+Error().stack;if(F.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;F=new Uint8Array(F);u.prototype.bg=F;F=b.files;for(var H=0;H<F.length;++H)u.prototype.hf[F[H].filename].onload();p.removeRunDependency("datafile_index.data")}p.FS_createPath("/",
"data",!0,!0);p.FS_createPath("/","gfx",!0,!0);p.FS_createPath("/","music",!0,!0);p.FS_createPath("/","sound",!0,!0);u.prototype={hf:{},open:function(F,H){this.name=H;this.hf[H]=this;p.addRunDependency(`fp ${this.name}`)},onload:function(){this.finish(this.bg.subarray(this.start,this.end))},finish:function(F){p.FS_createDataFile(this.name,null,F,!0,!0,!0);p.removeRunDependency(`fp ${this.name}`);this.hf[this.name]=null}};for(var z=b.files,B=0;B<z.length;++B)(new u(z[B].start,z[B].end,z[B].audio||
0)).open("GET",z[B].filename);p.addRunDependency("datafile_index.data");p.preloadResults??(p.preloadResults={});p.preloadResults["index.data"]={Lh:!1};n?(v(n),n=null):l=v}"object"===typeof window?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var f=h.locateFile?h.locateFile("index.data",
""):"index.data",g=b.remote_package_size,l=null,n=h.getPreloadedPackage?h.getPreloadedPackage(f,g):null;n||c(f,g,p=>{l?(l(p),l=null):n=p},d);if(h.calledRun)e(h);else{let p;((p=h).preRun??(p.preRun=[])).push(e)}}({files:[{filename:"/data/credits.txt",start:0,end:1646},{filename:"/gfx/aimFighter1.png",start:1646,end:3095},{filename:"/gfx/aimFighter2.png",start:3095,end:4551},{filename:"/gfx/alienDevice.png",start:4551,end:4774},{filename:"/gfx/arrowEast.png",start:4774,end:4897},{filename:"/gfx/arrowNorth.png",
start:4897,end:5017},{filename:"/gfx/arrowNorthEast.png",start:5017,end:5143},{filename:"/gfx/arrowNorthWest.png",start:5143,end:5268},{filename:"/gfx/arrowSouth.png",start:5268,end:5388},{filename:"/gfx/arrowSouthEast.png",start:5388,end:5512},{filename:"/gfx/arrowSouthWest.png",start:5512,end:5637},{filename:"/gfx/arrowWest.png",start:5637,end:5759},{filename:"/gfx/asteroid1.png",start:5759,end:13747},{filename:"/gfx/asteroid2.png",start:13747,end:15941},{filename:"/gfx/asteroid3.png",start:15941,
end:18130},{filename:"/gfx/barrier.png",start:18130,end:18524},{filename:"/gfx/buyIcon.png",start:18524,end:18873},{filename:"/gfx/cargo1.png",start:18873,end:19726},{filename:"/gfx/chainLink.png",start:19726,end:19851},{filename:"/gfx/cloakShip1.png",start:19851,end:20813},{filename:"/gfx/cloakShip2.png",start:20813,end:21778},{filename:"/gfx/credits.jpg",start:21778,end:120591},{filename:"/gfx/cursor.png",start:120591,end:120877},{filename:"/gfx/dollar.png",start:120877,end:121154},{filename:"/gfx/drone1.png",
start:121154,end:121831},{filename:"/gfx/drone2.png",start:121831,end:122508},{filename:"/gfx/dualFighter1.png",start:122508,end:123133},{filename:"/gfx/dualFighter2.png",start:123133,end:123754},{filename:"/gfx/elec1.png",start:123754,end:123860},{filename:"/gfx/elec2.png",start:123860,end:123970},{filename:"/gfx/elec3.png",start:123970,end:124082},{filename:"/gfx/elec4.png",start:124082,end:124183},{filename:"/gfx/eliteFighter1.png",start:124183,end:125545},{filename:"/gfx/eliteFighter2.png",start:125545,
end:126906},{filename:"/gfx/escort1.png",start:126906,end:128181},{filename:"/gfx/escort2.png",start:128181,end:129459},{filename:"/gfx/evilUrsula1.png",start:129459,end:130752},{filename:"/gfx/evilUrsula2.png",start:130752,end:132026},{filename:"/gfx/execTrans1.png",start:132026,end:140934},{filename:"/gfx/execTrans2.png",start:140934,end:149803},{filename:"/gfx/explode05.png",start:149803,end:151083},{filename:"/gfx/explode06.png",start:151083,end:152708},{filename:"/gfx/explode07.png",start:152708,
end:154157},{filename:"/gfx/explode08.png",start:154157,end:154960},{filename:"/gfx/explode1.png",start:154960,end:155080},{filename:"/gfx/explode10.png",start:155080,end:155317},{filename:"/gfx/explode11.png",start:155317,end:155446},{filename:"/gfx/explode12.png",start:155446,end:155558},{filename:"/gfx/explode13.png",start:155558,end:155650},{filename:"/gfx/explode14.png",start:155650,end:155739},{filename:"/gfx/explode15.png",start:155739,end:155828},{filename:"/gfx/explode16.png",start:155828,
end:155920},{filename:"/gfx/explode2.png",start:155920,end:156148},{filename:"/gfx/explode3.png",start:156148,end:156374},{filename:"/gfx/explode4.png",start:156374,end:156596},{filename:"/gfx/explode9.png",start:156596,end:156705},{filename:"/gfx/eyananth.jpg",start:156705,end:206847},{filename:"/gfx/face_chris.png",start:206847,end:207423},{filename:"/gfx/face_crew.png",start:207423,end:208020},{filename:"/gfx/face_kline.png",start:208020,end:208687},{filename:"/gfx/face_krass.png",start:208687,
end:209436},{filename:"/gfx/face_phoebe.png",start:209436,end:210100},{filename:"/gfx/face_sid.png",start:210100,end:210653},{filename:"/gfx/face_ursula.png",start:210653,end:211334},{filename:"/gfx/firefly-big.png",start:211334,end:242305},{filename:"/gfx/firefly1.png",start:242305,end:243173},{filename:"/gfx/firefly2.png",start:243173,end:244044},{filename:"/gfx/friendArrowEast.png",start:244044,end:244172},{filename:"/gfx/friendArrowNorth.png",start:244172,end:244297},{filename:"/gfx/friendArrowNorthEast.png",
start:244297,end:244429},{filename:"/gfx/friendArrowNorthWest.png",start:244429,end:244560},{filename:"/gfx/friendArrowSouth.png",start:244560,end:244686},{filename:"/gfx/friendArrowSouthEast.png",start:244686,end:244814},{filename:"/gfx/friendArrowSouthWest.png",start:244814,end:244943},{filename:"/gfx/friendArrowWest.png",start:244943,end:245069},{filename:"/gfx/frigateBody1.png",start:245069,end:256333},{filename:"/gfx/frigateBody2.png",start:256333,end:267574},{filename:"/gfx/frigateGun11.png",
start:267574,end:270835},{filename:"/gfx/frigateGun12.png",start:270835,end:274067},{filename:"/gfx/frigateGun21.png",start:274067,end:276190},{filename:"/gfx/frigateGun22.png",start:276190,end:278314},{filename:"/gfx/gameover.png",start:278314,end:281281},{filename:"/gfx/goodTrans1.png",start:281281,end:282218},{filename:"/gfx/goodTrans2.png",start:282218,end:283156},{filename:"/gfx/greenDir.png",start:283156,end:283294},{filename:"/gfx/heart.png",start:283294,end:283562},{filename:"/gfx/icon1.png",
start:283562,end:283864},{filename:"/gfx/icon10.png",start:283864,end:285188},{filename:"/gfx/icon11.png",start:285188,end:285522},{filename:"/gfx/icon12.png",start:285522,end:285872},{filename:"/gfx/icon13.png",start:285872,end:286055},{filename:"/gfx/icon14.png",start:286055,end:287040},{filename:"/gfx/icon15.png",start:287040,end:288044},{filename:"/gfx/icon16.png",start:288044,end:289055},{filename:"/gfx/icon17.png",start:289055,end:290204},{filename:"/gfx/icon18.png",start:290204,end:290440},
{filename:"/gfx/icon19.png",start:290440,end:290621},{filename:"/gfx/icon2.png",start:290621,end:291950},{filename:"/gfx/icon20.png",start:291950,end:292229},{filename:"/gfx/icon21.png",start:292229,end:292917},{filename:"/gfx/icon22.png",start:292917,end:293119},{filename:"/gfx/icon23.png",start:293119,end:294071},{filename:"/gfx/icon24.png",start:294071,end:294283},{filename:"/gfx/icon25.png",start:294283,end:294591},{filename:"/gfx/icon26.png",start:294591,end:295061},{filename:"/gfx/icon3.png",
start:295061,end:295229},{filename:"/gfx/icon4.png",start:295229,end:295427},{filename:"/gfx/icon5.png",start:295427,end:296309},{filename:"/gfx/icon6.png",start:296309,end:296802},{filename:"/gfx/icon7.png",start:296802,end:297172},{filename:"/gfx/icon8.png",start:297172,end:297468},{filename:"/gfx/icon9.png",start:297468,end:298280},{filename:"/gfx/iconBase.png",start:298280,end:298495},{filename:"/gfx/kline11.png",start:298495,end:299182},{filename:"/gfx/kline12.png",start:299182,end:299873},{filename:"/gfx/klineText.png",
start:299873,end:300056},{filename:"/gfx/merc1.png",start:300056,end:301056},{filename:"/gfx/merc2.png",start:301056,end:302055},{filename:"/gfx/mine.png",start:302055,end:302663},{filename:"/gfx/mineBoss1.png",start:302663,end:307982},{filename:"/gfx/mineBoss2.png",start:307982,end:313279},{filename:"/gfx/mineBossWing11.png",start:313279,end:314200},{filename:"/gfx/mineBossWing12.png",start:314200,end:315123},{filename:"/gfx/mineBossWing21.png",start:315123,end:318768},{filename:"/gfx/mineBossWing22.png",
start:318768,end:322399},{filename:"/gfx/mineBossWing31.png",start:322399,end:326030},{filename:"/gfx/mineBossWing32.png",start:326030,end:329650},{filename:"/gfx/mineBossWing41.png",start:329650,end:330589},{filename:"/gfx/mineBossWing42.png",start:330589,end:331532},{filename:"/gfx/miner1.png",start:331532,end:333207},{filename:"/gfx/miner2.png",start:333207,end:334870},{filename:"/gfx/missileBoat1.png",start:334870,end:336939},{filename:"/gfx/missileBoat2.png",start:336939,end:339022},{filename:"/gfx/mobileCannon1.png",
start:339022,end:339471},{filename:"/gfx/mobileCannon2.png",start:339471,end:339920},{filename:"/gfx/mobileShield1.png",start:339920,end:340457},{filename:"/gfx/mobileShield2.png",start:340457,end:340996},{filename:"/gfx/mordor.jpg",start:340996,end:361503},{filename:"/gfx/ore1.png",start:361503,end:362203},{filename:"/gfx/ore2.png",start:362203,end:362939},{filename:"/gfx/ore3.png",start:362939,end:363652},{filename:"/gfx/phoebeText.png",start:363652,end:363856},{filename:"/gfx/planet_blue.png",
start:363856,end:364889},{filename:"/gfx/planet_green.png",start:364889,end:365900},{filename:"/gfx/planet_orange.png",start:365900,end:366858},{filename:"/gfx/planet_red.png",start:366858,end:367883},{filename:"/gfx/planet_sun.png",start:367883,end:370872},{filename:"/gfx/plasmaAmmo.png",start:370872,end:371160},{filename:"/gfx/plasmaDamage.png",start:371160,end:371639},{filename:"/gfx/plasmaGreen.png",start:371639,end:372784},{filename:"/gfx/plasmaRate.png",start:372784,end:373160},{filename:"/gfx/plasmaRed.png",
start:373160,end:373254},{filename:"/gfx/plutoBoss1.png",start:373254,end:374389},{filename:"/gfx/plutoBoss2.png",start:374389,end:375524},{filename:"/gfx/pod.png",start:375524,end:375933},{filename:"/gfx/prlogo.png",start:375933,end:381241},{filename:"/gfx/rebelCarrier1.png",start:381241,end:385137},{filename:"/gfx/rebelCarrier2.png",start:385137,end:389054},{filename:"/gfx/redDir.png",start:389054,end:389192},{filename:"/gfx/rocket.png",start:389192,end:389656},{filename:"/gfx/rocket1.png",start:389656,
end:389930},{filename:"/gfx/rocket2.png",start:389930,end:390196},{filename:"/gfx/rocketAmmo.png",start:390196,end:390830},{filename:"/gfx/sellIcon.png",start:390830,end:391221},{filename:"/gfx/sflogo.png",start:391221,end:404515},{filename:"/gfx/sid1.png",start:404515,end:404881},{filename:"/gfx/sid2.png",start:404881,end:405248},{filename:"/gfx/sidText.png",start:405248,end:405404},{filename:"/gfx/slaveTrans1.png",start:405404,end:406395},{filename:"/gfx/slaveTrans2.png",start:406395,end:407383},
{filename:"/gfx/smallFont.png",start:407383,end:408093},{filename:"/gfx/sol.jpg",start:408093,end:496438},{filename:"/gfx/spirit.jpg",start:496438,end:524382},{filename:"/gfx/splitBoss11.png",start:524382,end:525601},{filename:"/gfx/splitBoss12.png",start:525601,end:526809},{filename:"/gfx/splitBoss21.png",start:526809,end:527601},{filename:"/gfx/splitBoss22.png",start:527601,end:528394},{filename:"/gfx/splitBoss31.png",start:528394,end:529359},{filename:"/gfx/splitBoss32.png",start:529359,end:530322},
{filename:"/gfx/startUp.jpg",start:530322,end:665281},{filename:"/gfx/stunBolt.png",start:665281,end:665417},{filename:"/gfx/superCharge.png",start:665417,end:665934},{filename:"/gfx/targetText.png",start:665934,end:666140},{filename:"/gfx/transport1.png",start:666140,end:667090},{filename:"/gfx/transport2.png",start:667090,end:668043},{filename:"/gfx/tug1.png",start:668043,end:669384},{filename:"/gfx/tug2.png",start:669384,end:670725},{filename:"/gfx/ursulaText.png",start:670725,end:670923},{filename:"/gfx/wingmate1.png",
start:670923,end:672212},{filename:"/gfx/wingmate2.png",start:672212,end:673496},{filename:"/music/3DParadise.mod",start:673496,end:789402},{filename:"/music/Artificial.mod",start:789402,end:978076},{filename:"/music/DigitalInferno.mod",start:978076,end:1103192},{filename:"/music/Frantic.mod",start:1103192,end:1244830},{filename:"/music/HardTranceDub.mod",start:1244830,end:1334624},{filename:"/music/IntoTheMachine.mod",start:1334624,end:1506318},{filename:"/music/LoopsAndTings.mod",start:1506318,
end:1709806},{filename:"/music/Lunatic.mod",start:1709806,end:1831956},{filename:"/music/Platinum.mod",start:1831956,end:2041964},{filename:"/music/Solace.s3m",start:2041964,end:2394846},{filename:"/music/TempoTrance.mod",start:2394846,end:2593490},{filename:"/music/ToxicFriend.mod",start:2593490,end:2753524},{filename:"/music/TranceGeneration.mod",start:2753524,end:2917326},{filename:"/music/Wybierak.mod",start:2917326,end:2950768},{filename:"/sound/beamLaser.ogg",start:2950768,end:2971798,audio:1},
{filename:"/sound/cloak.ogg",start:2971798,end:3011922,audio:1},{filename:"/sound/clock.ogg",start:3011922,end:3015711,audio:1},{filename:"/sound/explode.ogg",start:3015711,end:3061900,audio:1},{filename:"/sound/explode2.ogg",start:3061900,end:3096583,audio:1},{filename:"/sound/explode3.ogg",start:3096583,end:3128279,audio:1},{filename:"/sound/explode4.ogg",start:3128279,end:3156402,audio:1},{filename:"/sound/flyby.ogg",start:3156402,end:3205454,audio:1},{filename:"/sound/hyperSpace.ogg",start:3205454,
end:3229233,audio:1},{filename:"/sound/item.ogg",start:3229233,end:3235604,audio:1},{filename:"/sound/laser.ogg",start:3235604,end:3240635,audio:1},{filename:"/sound/maledeath.ogg",start:3240635,end:3274975,audio:1},{filename:"/sound/missile.ogg",start:3274975,end:3313579,audio:1},{filename:"/sound/missile2.ogg",start:3313579,end:3342153,audio:1},{filename:"/sound/plasma.ogg",start:3342153,end:3353205,audio:1},{filename:"/sound/plasma2.ogg",start:3353205,end:3398638,audio:1},{filename:"/sound/plasma3.ogg",
start:3398638,end:3408738,audio:1},{filename:"/sound/shield.ogg",start:3408738,end:3419845,audio:1}],remote_package_size:3419845})})();var ba=Object.assign({},h),ca=[],da="./this.program",ea="",fa;"undefined"!=typeof document&&document.currentScript&&(ea=document.currentScript.src);ea=ea.startsWith("blob:")?"":ea.substr(0,ea.replace(/[?#].*/,"").lastIndexOf("/")+1);fa=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};
var ha=h.print||console.log.bind(console),k=h.printErr||console.error.bind(console);Object.assign(h,ba);ba=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);var ia=h.wasmBinary,ja,ka=!1,la,m,q,ma,na,r,t,w,oa,x,pa=a=>a.startsWith("data:application/octet-stream;base64,"),qa=[],ra=[],sa=[],ta=[];function ua(){var a=h.preRun.shift();qa.unshift(a)}var va=0,wa=null;function xa(){va++;h.monitorRunDependencies?.(va)}
function ya(){va--;h.monitorRunDependencies?.(va);if(0==va&&wa){var a=wa;wa=null;a()}}function za(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);ka=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Aa;async function Ba(a){if(!ia)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==Aa&&ia)a=new Uint8Array(ia);else throw"both async and sync fetching of the wasm failed";return a}
async function Ca(a,b){try{var c=await Ba(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),za(d)}}async function Da(a){var b=Aa;if(!ia&&"function"==typeof WebAssembly.instantiateStreaming&&!pa(b))try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return Ca(b,a)}
var Ma={388764:a=>{a=(a?y(q,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");return Ga(Ha(a),"i8",Ia)},388989:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,389136:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,389370:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};
b.cf||("undefined"!==typeof AudioContext?b.cf=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.cf=new webkitAudioContext),b.cf&&"undefined"===typeof navigator.userActivation&&Ja(b.cf));return void 0===b.cf?-1:0},389922:()=>h.SDL2.cf.sampleRate,389990:(a,b,c,d)=>{function e(){}function f(l){void 0!==g.capture.rf&&(clearInterval(g.capture.rf),g.capture.rf=void 0,g.capture.Df=void 0);g.capture.lg=g.cf.createMediaStreamSource(l);g.capture.qf=g.cf.createScriptProcessor(b,a,1);g.capture.qf.onaudioprocess=
function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.dg=n.inputBuffer,Ka(c,[d]))};g.capture.lg.connect(g.capture.qf);g.capture.qf.connect(g.cf.destination);g.capture.stream=l}var g=h.SDL2;g.capture.Df=g.cf.createBuffer(a,b,g.cf.sampleRate);g.capture.Df.getChannelData(0).fill(0);g.capture.rf=setInterval(function(){g.capture.dg=g.capture.Df;Ka(c,[d])},b/g.cf.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,
video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},391683:(a,b,c,d)=>{var e=h.SDL2;e.audio.qf=e.cf.createScriptProcessor(b,0,a);e.audio.qf.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.rf&&(clearInterval(e.audio.rf),e.audio.rf=void 0,e.audio.Df=void 0),e.audio.Qf=f.outputBuffer,Ka(c,[d]))};e.audio.qf.connect(e.cf.destination);"suspended"===e.cf.state&&(e.audio.Df=e.cf.createBuffer(a,b,e.cf.sampleRate),
e.audio.Df.getChannelData(0).fill(0),e.audio.rf=setInterval(function(){"undefined"!==typeof navigator.userActivation&&navigator.userActivation.hasBeenActive&&e.cf.resume();e.audio.Qf=e.audio.Df;Ka(c,[d]);e.audio.Qf=void 0},b/e.cf.sampleRate*1E3))},392858:(a,b)=>{for(var c=h.SDL2,d=c.capture.dg.numberOfChannels,e=0;e<d;++e){var f=c.capture.dg.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=
0;g<b;++g)La(a+4*g,f[g]);else for(g=0;g<b;++g)La(a+4*(g*d+e),f[g])}},393463:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=c.audio.Qf.numberOfChannels,e=0;e<d;++e){var f=c.audio.Qf.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=w[a+(g*d+e)]}},393952:a=>{var b=h.SDL2;if(a){void 0!==b.capture.rf&&clearInterval(b.capture.rf);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();
for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.qf&&(b.capture.qf.onaudioprocess=function(){},b.capture.qf.disconnect());void 0!==b.capture.lg&&b.capture.lg.disconnect();b.capture=void 0}else void 0!=b.audio.qf&&b.audio.qf.disconnect(),void 0!==b.audio.rf&&clearInterval(b.audio.rf),b.audio=void 0;void 0!==b.cf&&void 0===b.audio&&void 0===b.capture&&(b.cf.close(),b.cf=void 0)},394958:()=>window.innerWidth,394988:()=>window.innerHeight,395019:(a,b,c)=>{h.SDL2||(h.SDL2=
{});var d=h.SDL2;d.Sg!==h.canvas&&(d.Pf=h.createContext(h.canvas,!1,!0),d.Sg=h.canvas);if(d.w!==a||d.h!==b||d.gh!==d.Pf)d.image=d.Pf.createImageData(a,b),d.w=a,d.h=b,d.gh=d.Pf;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=r[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Wg!==a&&(d.Vg=new Int32Array(a.buffer),d.Xg=new Uint8Array(a.buffer),d.Wg=a),a=d.Vg,c=a.length,a.set(r.subarray(b,b+c)),
a=d.Xg,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Pf.putImageData(d.image,0,0)},396487:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e/=4;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;l<n;){var p=r[e];b[l]=p&
255;b[l+1]=p>>8&255;b[l+2]=p>>16&255;b[l+3]=p>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(r.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=A(c.length+1);C(c,q,d,c.length+1);return d},397475:a=>{h.canvas&&(h.canvas.style.cursor=a?y(q,a):"")},397558:()=>{h.canvas&&(h.canvas.style.cursor="none")}};
class Na{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Oa=a=>{for(;0<a.length;)a.shift()(h)},Pa=h.noExitRuntime||!0;
function La(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":m[a]=b;break;case "i8":m[a]=b;break;case "i16":ma[a>>1]=b;break;case "i32":r[a>>2]=b;break;case "i64":oa[a>>3]=BigInt(b);break;case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":t[a>>2]=b;break;default:za(`invalid type for setValue: ${c}`)}}
var Qa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ra=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Qa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Sa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Ta=a=>a&&
a.match(/([^\/]+|\/)\/*$/)[1],Ua=()=>a=>crypto.getRandomValues(a),Va=a=>{(Va=Ua())(a)},Xa=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:Wa;if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Qa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ya="undefined"!=typeof TextDecoder?new TextDecoder:void 0,y=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ya)return Ya.decode(a.subarray(b,
c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Za=[],$a=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},C=(a,b,c,d)=>{if(!(0<d))return 0;var e=
c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function Ha(a,b){var c=Array($a(a)+1);a=C(a,c,0,c.length);b&&(c.length=a);return c}var bb=[];
function cb(a,b){bb[a]={input:[],gf:[],yf:b};db(a,eb)}
var eb={open(a){var b=bb[a.node.Kf];if(!b)throw new D(43);a.bf=b;a.seekable=!1},close(a){a.bf.yf.Rf(a.bf)},Rf(a){a.bf.yf.Rf(a.bf)},read(a,b,c,d){if(!a.bf||!a.bf.yf.Dg)throw new D(60);for(var e=0,f=0;f<d;f++){try{var g=a.bf.yf.Dg(a.bf)}catch(l){throw new D(29);}if(void 0===g&&0===e)throw new D(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.Af=Date.now());return e},write(a,b,c,d){if(!a.bf||!a.bf.yf.ng)throw new D(60);try{for(var e=0;e<d;e++)a.bf.yf.ng(a.bf,b[c+e])}catch(f){throw new D(29);
}d&&(a.node.kf=a.node.jf=Date.now());return e}},fb={Dg(){a:{if(!Za.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Za=Ha(a,!0)}a=Za.shift()}return a},ng(a,b){null===b||10===b?(ha(y(a.gf)),a.gf=[]):0!=b&&a.gf.push(b)},Rf(a){a.gf&&0<a.gf.length&&(ha(y(a.gf)),a.gf=[])},kh(){return{Bh:25856,Dh:5,Ah:191,Ch:35387,zh:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},lh(){return 0},
mh(){return[24,80]}},gb={ng(a,b){null===b||10===b?(k(y(a.gf)),a.gf=[]):0!=b&&a.gf.push(b)},Rf(a){a.gf&&0<a.gf.length&&(k(y(a.gf)),a.gf=[])}},ib=a=>{a=65536*Math.ceil(a/65536);var b=hb(65536,a);b&&q.fill(0,b,b+a);return b};function jb(a,b){var c=a.ce?a.ce.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ce,a.ce=new Uint8Array(b),0<a.df&&a.ce.set(c.subarray(0,a.df),0))}
var E={tf:null,xf(){return E.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new D(63);E.tf||(E.tf={dir:{node:{wf:E.af.wf,uf:E.af.uf,If:E.af.If,Wf:E.af.Wf,Mg:E.af.Mg,ag:E.af.ag,Zf:E.af.Zf,og:E.af.og,$f:E.af.$f},stream:{sf:E.$e.sf}},file:{node:{wf:E.af.wf,uf:E.af.uf},stream:{sf:E.$e.sf,read:E.$e.read,write:E.$e.write,wg:E.$e.wg,Jf:E.$e.Jf,Yf:E.$e.Yf}},link:{node:{wf:E.af.wf,uf:E.af.uf,Lf:E.af.Lf},stream:{}},Ag:{node:{wf:E.af.wf,uf:E.af.uf},stream:kb}});
c=lb(a,b,c,d);G(c.mode)?(c.af=E.tf.dir.node,c.$e=E.tf.dir.stream,c.ce={}):32768===(c.mode&61440)?(c.af=E.tf.file.node,c.$e=E.tf.file.stream,c.df=0,c.ce=null):40960===(c.mode&61440)?(c.af=E.tf.link.node,c.$e=E.tf.link.stream):8192===(c.mode&61440)&&(c.af=E.tf.Ag.node,c.$e=E.tf.Ag.stream);c.Af=c.kf=c.jf=Date.now();a&&(a.ce[b]=c,a.Af=a.kf=a.jf=c.Af);return c},Nh(a){return a.ce?a.ce.subarray?a.ce.subarray(0,a.df):new Uint8Array(a.ce):new Uint8Array(0)},af:{wf(a){var b={};b.Zg=8192===(a.mode&61440)?a.id:
1;b.ih=a.id;b.mode=a.mode;b.ph=1;b.uid=0;b.eh=0;b.Kf=a.Kf;G(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.df:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Af=new Date(a.Af);b.kf=new Date(a.kf);b.jf=new Date(a.jf);b.Qg=4096;b.Rg=Math.ceil(b.size/b.Qg);return b},uf(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.df!=b&&(0==b?(a.ce=null,a.df=0):(c=a.ce,a.ce=new Uint8Array(b),c&&a.ce.set(c.subarray(0,Math.min(b,a.df))),a.df=b)))},If(){throw E.Bg;
},Wf(a,b,c,d){return E.createNode(a,b,c,d)},Mg(a,b,c){try{var d=mb(b,c)}catch(f){}if(d){if(G(a.mode))for(var e in d.ce)throw new D(55);nb(d)}delete a.parent.ce[a.name];b.ce[c]=a;a.name=c;b.jf=b.kf=a.parent.jf=a.parent.kf=Date.now()},ag(a,b){delete a.ce[b];a.jf=a.kf=Date.now()},Zf(a,b){var c=mb(a,b),d;for(d in c.ce)throw new D(55);delete a.ce[b];a.jf=a.kf=Date.now()},og(a){return[".","..",...Object.keys(a.ce)]},$f(a,b,c){a=E.createNode(a,b,41471,0);a.link=c;return a},Lf(a){if(40960!==(a.mode&61440))throw new D(28);
return a.link}},$e:{read(a,b,c,d,e){var f=a.node.ce;if(e>=a.node.df)return 0;a=Math.min(a.node.df-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.kf=a.jf=Date.now();if(b.subarray&&(!a.ce||a.ce.subarray)){if(f)return a.ce=b.subarray(c,c+d),a.df=d;if(0===a.df&&0===e)return a.ce=b.slice(c,c+d),a.df=d;if(e+d<=a.df)return a.ce.set(b.subarray(c,c+d),e),d}jb(a,e+d);if(a.ce.subarray&&b.subarray)a.ce.set(b.subarray(c,
c+d),e);else for(f=0;f<d;f++)a.ce[e+f]=b[c+f];a.df=Math.max(a.df,e+d);return d},sf(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.df);if(0>b)throw new D(28);return b},wg(a,b,c){jb(a.node,b+c);a.node.df=Math.max(a.node.df,b+c)},Jf(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new D(43);a=a.node.ce;if(e&2||!a||a.buffer!==m.buffer){d=!0;e=ib(b);if(!e)throw new D(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);m.set(a,e)}}else d=
!1,e=a.byteOffset;return{Lg:e,xg:d}},Yf(a,b,c,d){E.$e.write(a,b,0,d,c,!1);return 0}}},ob=async a=>{a=await fa(a);return new Uint8Array(a)},pb=h.preloadPlugins||[],sb=(a,b,c,d)=>{"undefined"!=typeof qb&&rb();var e=!1;pb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},ub=(a,b,c,d,e,f,g,l,n,p)=>{function u(B){function F(H){p?.();l||tb(a,b,H,d,e,n);f?.();ya(z)}sb(B,v,F,()=>{g?.();ya(z)})||F(B)}var v=b?Xa(Ra(a+"/"+b)):a,z=`cp ${v}`;xa(z);"string"==typeof c?ob(c).then(u,g):u(c)},vb=
(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},wb=null,xb={},yb=[],zb=1,Ab=null,Wa="/",Bb=!1,Cb=!0,D=class{name="ErrnoError";constructor(a){this.ef=a}},Db={},Eb=class{hf={};node=null;get flags(){return this.hf.flags}set flags(a){this.hf.flags=a}get position(){return this.hf.position}set position(a){this.hf.position=a}},Ib=class{af={};$e={};Ef=null;constructor(a,b,c,d){a||=this;this.parent=a;this.xf=a.xf;this.id=zb++;this.name=b;this.mode=c;this.Kf=d;this.Af=this.kf=this.jf=Date.now()}get read(){return 365===
(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get nh(){return G(this.mode)}get Fg(){return 8192===(this.mode&61440)}};
function Jb(a,b={}){if(!a)throw new D(44);b.fg??(b.fg=!0);"/"===a.charAt(0)||(a=Wa+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(l=>!!l);for(var d=wb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])e=Sa(e),d=d.parent;else{e=Ra(e+"/"+a[f]);try{d=mb(d,a[f])}catch(l){if(44===l?.ef&&g&&b.qh)return{path:e};throw l;}!d.Ef||g&&!b.fg||(d=d.Ef.root);if(40960===(d.mode&61440)&&(!g||b.Hf)){if(!d.af.Lf)throw new D(52);d=d.af.Lf(d);"/"===d.charAt(0)||(d=
Sa(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new D(32);}function Kb(a){for(var b;;){if(a===a.parent)return a=a.xf.Ig,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Lb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Ab.length}function nb(a){var b=Lb(a.parent.id,a.name);if(Ab[b]===a)Ab[b]=a.Ff;else for(b=Ab[b];b;){if(b.Ff===a){b.Ff=a.Ff;break}b=b.Ff}}
function mb(a,b){var c=G(a.mode)?(c=Mb(a,"x"))?c:a.af.If?0:2:54;if(c)throw new D(c);for(c=Ab[Lb(a.id,b)];c;c=c.Ff){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.af.If(a,b)}function lb(a,b,c,d){a=new Ib(a,b,c,d);b=Lb(a.parent.id,a.name);a.Ff=Ab[b];return Ab[b]=a}function G(a){return 16384===(a&61440)}function Nb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Mb(a,b){if(Cb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ob(a,b){if(!G(a.mode))return 54;try{return mb(a,b),20}catch(c){}return Mb(a,"wx")}function Pb(a,b,c){try{var d=mb(a,b)}catch(e){return e.ef}if(a=Mb(a,"wx"))return a;if(c){if(!G(d.mode))return 54;if(d===d.parent||Kb(d)===Wa)return 10}else if(G(d.mode))return 31;return 0}function Qb(a){if(!a)throw new D(63);return a}
function Rb(a){a=yb[a];if(!a)throw new D(8);return a}function Sb(a,b=-1){a=Object.assign(new Eb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!yb[b])break a;throw new D(33);}a.fd=b;return yb[b]=a}function Tb(a,b=-1){a=Sb(a,b);a.$e?.Jh?.(a);return a}var kb={open(a){a.$e=xb[a.node.Kf].$e;a.$e.open?.(a)},sf(){throw new D(70);}};function db(a,b){xb[a]={$e:b}}
function Ub(a,b){var c="/"===b;if(c&&wb)throw new D(10);if(!c&&b){var d=Jb(b,{fg:!1});b=d.path;d=d.node;if(d.Ef)throw new D(10);if(!G(d.mode))throw new D(54);}b={type:a,Sh:{},Ig:b,oh:[]};a=a.xf(b);a.xf=b;b.root=a;c?wb=a:d&&(d.Ef=b,d.xf&&d.xf.oh.push(b))}function Vb(a,b,c){var d=Jb(a,{parent:!0}).node;a=Ta(a);if(!a)throw new D(28);if("."===a||".."===a)throw new D(20);var e=Ob(d,a);if(e)throw new D(e);if(!d.af.Wf)throw new D(63);return d.af.Wf(d,a,b,c)}
function Wb(a,b=438){return Vb(a,b&4095|32768,0)}function Xb(a,b=511){return Vb(a,b&1023|16384,0)}function Yb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Vb(a,b|8192,c)}function Zb(a,b){if(!Xa(a))throw new D(44);var c=Jb(b,{parent:!0}).node;if(!c)throw new D(44);b=Ta(b);var d=Ob(c,b);if(d)throw new D(d);if(!c.af.$f)throw new D(63);c.af.$f(c,b,a)}
function $b(a){var b=Jb(a,{parent:!0}).node;a=Ta(a);var c=mb(b,a),d=Pb(b,a,!0);if(d)throw new D(d);if(!b.af.Zf)throw new D(63);if(c.Ef)throw new D(10);b.af.Zf(b,a);nb(c)}function ac(a){var b=Jb(a,{parent:!0}).node;if(!b)throw new D(44);a=Ta(a);var c=mb(b,a),d=Pb(b,a,!1);if(d)throw new D(d);if(!b.af.ag)throw new D(63);if(c.Ef)throw new D(10);b.af.ag(b,a);nb(c)}function bc(a,b){a=Jb(a,{Hf:!b}).node;return Qb(a.af.wf)(a)}
function cc(a,b){a="string"==typeof a?Jb(a,{Hf:!0}).node:a;Qb(a.af.uf)(a,{mode:b&4095|a.mode&-4096,jf:Date.now(),Ih:void 0})}
function dc(a,b,c=438){if(""===a)throw new D(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=Jb(a,{Hf:!(b&131072),qh:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new D(20);}else{if(e)throw new D(31);d=Vb(a,c|511,0);f=!0}if(!d)throw new D(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!G(d.mode))throw new D(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:G(d.mode)&&("r"!==Nb(b)||b&576)?31:Mb(d,Nb(b)):44))throw new D(e);if(b&512&&!f){e=d;e="string"==typeof e?Jb(e,{Hf:!0}).node:e;if(G(e.mode))throw new D(31);if(32768!==(e.mode&61440))throw new D(28);var g=Mb(e,"w");if(g)throw new D(g);Qb(e.af.uf)(e,{size:0,timestamp:Date.now()})}b&=-131713;e=Sb({node:d,path:Kb(d),flags:b,seekable:!0,position:0,$e:d.$e,uh:[],error:!1});e.$e.open&&e.$e.open(e);f&&cc(d,c&511);!h.logReadFiles||b&1||a in Db||(Db[a]=1);return e}
function ec(a){if(null===a.fd)throw new D(8);a.ig&&(a.ig=null);try{a.$e.close&&a.$e.close(a)}catch(b){throw b;}finally{yb[a.fd]=null}a.fd=null}function fc(a,b,c){if(null===a.fd)throw new D(8);if(!a.seekable||!a.$e.sf)throw new D(70);if(0!=c&&1!=c&&2!=c)throw new D(28);a.position=a.$e.sf(a,b,c);a.uh=[]}
function gc(a,b,c,d,e,f){if(0>d||0>e)throw new D(28);if(null===a.fd)throw new D(8);if(0===(a.flags&2097155))throw new D(8);if(G(a.node.mode))throw new D(31);if(!a.$e.write)throw new D(28);a.seekable&&a.flags&1024&&fc(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new D(70);b=a.$e.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function hc(a,b){a="string"==typeof a?a:Kb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ra(a+"/"+c);try{Xb(d)}catch(e){}a=d}}return d}function ic(a,b,c,d){a=Ra(("string"==typeof a?a:Kb(a))+"/"+b);return Wb(a,vb(c,d))}
function tb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Kb(a),g=b?Ra(a+"/"+b):a);a=vb(d,e);g=Wb(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}cc(g,a|146);b=dc(g,577);gc(b,c,0,c.length,0,f);ec(b);cc(g,a)}}
function jc(a,b,c,d){a=Ra(("string"==typeof a?a:Kb(a))+"/"+b);b=vb(!!c,!!d);jc.Gg??(jc.Gg=64);var e=jc.Gg++<<8|0;db(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,l,n){for(var p=0,u=0;u<n;u++){try{var v=c()}catch(z){throw new D(29);}if(void 0===v&&0===p)throw new D(6);if(null===v||void 0===v)break;p++;g[l+u]=v}p&&(f.node.Af=Date.now());return p},write(f,g,l,n){for(var p=0;p<n;p++)try{d(g[l+p])}catch(u){throw new D(29);}n&&(f.node.kf=f.node.jf=Date.now());return p}});return Yb(a,
b,e)}function kc(a){if(!(a.Fg||a.nh||a.link||a.ce)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.ce=(void 0)(a.url),a.df=a.ce.length}catch(b){throw new D(29);}}}
function lc(a,b,c,d,e){function f(n,p,u,v,z){n=n.node.ce;if(z>=n.length)return 0;v=Math.min(n.length-z,v);if(n.slice)for(var B=0;B<v;B++)p[u+B]=n[z+B];else for(B=0;B<v;B++)p[u+B]=n.get(z+B);return v}if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={Fg:!1,url:c};var g=ic(a,b,d,e);c.ce?g.ce=c.ce:c.url&&(g.ce=null,g.url=c.url);Object.defineProperties(g,{df:{get:function(){return this.ce.length}}});
var l={};Object.keys(g.$e).forEach(n=>{var p=g.$e[n];l[n]=(...u)=>{kc(g);return p(...u)}});l.read=(n,p,u,v,z)=>{kc(g);return f(n,p,u,v,z)};l.Jf=(n,p,u)=>{kc(g);var v=ib(p);if(!v)throw new D(48);f(n,m,v,p,u);return{Lg:v,xg:!0}};g.$e=l;return g}var I={};function mc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?Wa:Rb(a).path;if(0==b.length){if(!c)throw new D(44);return a}return a+"/"+b}
function nc(a,b){r[a>>2]=b.Zg;r[a+4>>2]=b.mode;t[a+8>>2]=b.ph;r[a+12>>2]=b.uid;r[a+16>>2]=b.eh;r[a+20>>2]=b.Kf;oa[a+24>>3]=BigInt(b.size);r[a+32>>2]=4096;r[a+36>>2]=b.Rg;var c=b.Af.getTime(),d=b.kf.getTime(),e=b.jf.getTime();oa[a+40>>3]=BigInt(Math.floor(c/1E3));t[a+48>>2]=c%1E3*1E6;oa[a+56>>3]=BigInt(Math.floor(d/1E3));t[a+64>>2]=d%1E3*1E6;oa[a+72>>3]=BigInt(Math.floor(e/1E3));t[a+80>>2]=e%1E3*1E6;oa[a+88>>3]=BigInt(b.ih);return 0}
var oc=void 0,pc=()=>{var a=r[+oc>>2];oc+=4;return a},qc=0,rc={},sc=a=>{if(!(a instanceof Na||"unwind"==a))throw a;},tc=a=>{la=a;Pa||0<qc||(h.onExit?.(a),ka=!0);throw new Na(a);},uc=a=>{la=a;tc(a)},vc=()=>{if(!(Pa||0<qc))try{var a=la;la=a;tc(a)}catch(b){sc(b)}},wc=a=>{if(!ka)try{a(),vc()}catch(b){sc(b)}},xc=(a,b)=>setTimeout(()=>{wc(a)},b),yc=!1,zc=!1,Ac=[],Bc={};
function rb(){function a(){zc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Dc){Dc=!0;pb.push({canHandle:function(c){return!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:Ec(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Ec(d)}));var l=URL.createObjectURL(g),n=new Image;n.onload=()=>{var p=
document.createElement("canvas");p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);Bc[d]=p;URL.revokeObjectURL(l);e?.(c)};n.onerror=()=>{k(`Image ${l} could not be decoded`);f?.()};n.src=l}});pb.push({canHandle:function(c){return!h.noAudioDecoding&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,l=URL.createObjectURL(new Blob([c],{type:Ec(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!g){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="",u=0,v=0,z=0;z<c.length;z++)for(u=u<<8|c[z],v+=8;6<=v;){var B=u>>v-6&63;v-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[B]}2==v?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],p+="=="):4==v&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],p+="=");n.src="data:audio/x-"+d.substr(-3)+";base64,"+p;f(n)}};n.src=l;xc(()=>{f(n)},1E4)}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!zc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Fc=!1,Gc=void 0,Hc=void 0;function Ic(){if(!yc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}
function Ec(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Jc=[];function Kc(){var a=h.canvas;Jc.forEach(b=>b(a.width,a.height))}
function Lc(a,b,c){b&&c?(a.wh=b,a.fh=c):(b=a.wh,c=a.fh);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Hc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var qb={},Dc,J=12288,Mc=!1,Nc=0,Oc=0,Pc=0,K={alpha:!1,depth:!1,stencil:!1,antialias:!1},Qc={},Rc,L,Sc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Tc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Uc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Vc=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Wc=1,Xc=[],M=[],Yc=[],Zc=[],$c=[],N=[],ad=[],bd=[],cd=[],dd={},ed=4,fd=0,gd=a=>{for(var b=Wc++,c=a.length;c<b;c++)a[c]=null;return b},hd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=L[c](),g=f&&gd(d);f?(f.name=g,d[g]=f):O||=1282;r[b+4*e>>2]=g}},kd=(a,b)=>{a.hf||(a.hf=a.getContext,a.getContext=function(d,e){e=a.hf(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?jd(c,b):0},jd=(a,b)=>
{var c=gd(bd),d={handle:c,attributes:b,version:b.Hg,zf:a};a.canvas&&(a.canvas.Gf=d);bd[c]=d;("undefined"==typeof b.$g||b.$g)&&ld(d);return c},nd=a=>{md=bd[a];h.ctx=L=md?.zf},ld=a=>{a||=md;if(!a.hh){a.hh=!0;var b=a.zf;b.Rh=b.getExtension("WEBGL_multi_draw");b.bh=b.getExtension("EXT_polygon_offset_clamp");b.ah=b.getExtension("EXT_clip_control");b.vh=b.getExtension("WEBGL_polygon_mode");Sc(b);Tc(b);Uc(b);b.vf=b.getExtension("EXT_disjoint_timer_query");Vc(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},od={},O,md,pd=a=>{var b=$a(a)+1,c=A(b);c&&C(a,q,c,b);return c},Ed=a=>{function b(){return c<qd?(vc(),!1):!0}rd=a;var c=qd;sd=!1;td=function(){if(!ka)if(0<ud.length){var d=ud.shift();d.Mh(d.xh);if(vd){var e=vd,f=0==e%1?e-1:Math.floor(e);vd=d.Fh?f:(8*e+(f+.5))/9}h.setStatus&&(d=h.statusMessage||"Please wait...",e=vd??0,f=wd.Kh??0,e?e<f?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(d):h.setStatus(""));b()&&setTimeout(td,0)}else if(b())if(xd=xd+1|0,1==
yd&&1<zd&&0!=xd%zd)Ad();else{0==yd&&(Bd=performance.now());a:if(!ka){for(d of Cd)if(!1===d())break a;wc(a);for(e of Dd)e()}b()&&Ad()}}},sd=!1,Ad=null,qd=0,rd=null,yd=0,zd=0,xd=0,ud=[],Cd=[],Dd=[];function Fd(){Ad=null;qd++}function Gd(){qd++;var a=yd,b=zd,c=rd;rd=null;Ed(c);Hd(a,b);Ad()}var Id=0;function Jd(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Id)Id=b+1E3/60;else for(;b+2>=Id;)Id+=1E3/60;setTimeout(a,Math.max(Id-b,0))}}
var wd={},td,vd,Bd,Kd,Hd=(a,b)=>{yd=a;zd=b;if(rd)if(sd||=!0,0==a)Ad=function(){setTimeout(td,Math.max(0,Bd+b-performance.now())|0)};else if(1==a)Ad=function(){Jd(td)};else if(2==a){if("undefined"==typeof Kd)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Kd=d=>{c.push(d);postMessage("setimmediate","*")}}else Kd=setImmediate;Ad=function(){Kd(td)}}},Ld=[],Md=(a,b)=>{Ld.length=
0;for(var c;c=q[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Ld.push(112==c?t[b>>2]:106==c?oa[b>>3]:105==c?r[b>>2]:x[b>>3]);b+=d?8:4}return Ld};function Nd(a){var b=P.nf[a];b.target.removeEventListener(b.ff,b.Cg,b.lf);P.nf.splice(a,1)}function Od(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of P.Bf)if(e.qg==a&&d(e.yg,c))return;P.Bf.push({qg:a,Kg:b,yg:c});P.Bf.sort((f,g)=>f.Kg<g.Kg)}function Pd(a){P.Bf=P.Bf.filter(b=>b.qg!=a)}
function Qd(){return navigator.userActivation?navigator.userActivation.isActive:P.jg&&P.Tg.Nf}function Rd(){if(Qd()){var a=P.Bf;P.Bf=[];for(var b of a)b.qg(...b.yg)}}function Sd(a){if(!a.target)return-4;if(a.mf)a.Cg=function(c){++P.jg;P.Tg=a;Rd();a.pf(c);Rd();--P.jg},a.target.addEventListener(a.ff,a.Cg,a.lf),P.nf.push(a);else for(var b=0;b<P.nf.length;++b)P.nf[b].target==a.target&&P.nf[b].ff==a.ff&&Nd(b--);return 0}
function Td(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var P={yh:0,hg:0,kg:0,Xf:0,vg:0,sg:0,eg:0,Hh:0,Th:0,Gh:0,gg:0,mg:0,ug:0,rg:0,Ph(a,b,c){m.set(m.subarray(b,b+c),a)},Uh(){for(;P.nf.length;)Nd(P.nf.length-1);P.Bf=[]},jg:0,Bf:[],nf:[],sh:(a,b)=>{for(var c=0;c<P.nf.length;++c)P.nf[c].target!=a||b&&b!=P.nf[c].ff||Nd(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Ud={},Vd=[0,document,window],Q=a=>{a=2<a?a?y(q,a):"":a;return Vd[a]||document.querySelector(a)},Xd=a=>{var b=$a(a)+1,c=Wd(b);C(a,q,c,b);return c},
Yd=a=>{var b=R(),c=Wd(8),d=c+4;a=Xd(a.id);if(a=Q(a))r[c>>2]=a.width,r[d>>2]=a.height;c=[r[c>>2],r[d>>2]];S(b);return c},Zd=(a,b,c)=>{a=Q(a);if(!a)return-4;a.width=b;a.height=c;return 0},$d=(a,b,c)=>{if(a.Eh){var d=R();a=Xd(a.id);Zd(a,b,c);S(d)}else a.width=b,a.height=c},ae=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),$d(a,d,e),a.style.width=f,a.style.height=
g,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=u,a.style.paddingTop=v,a.style.paddingBottom=z,a.style.marginLeft=B,a.style.marginRight=F,a.style.marginTop=H,a.style.marginBottom=Y,document.body.style.margin=Gb,document.documentElement.style.overflow=ab,document.body.scroll=Fb,a.style.Cf=X,a.Gf&&a.Gf.zf.viewport(0,0,d,e),Ud.Of&&T(Ud.Of,37,0,Ud.zg))}var c=Yd(a),d=c[0],e=c[1],f=a.style.width,
g=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,u=a.style.paddingRight,v=a.style.paddingTop,z=a.style.paddingBottom,B=a.style.marginLeft,F=a.style.marginRight,H=a.style.marginTop,Y=a.style.marginBottom,Gb=document.body.style.margin,ab=document.documentElement.style.overflow,Fb=document.body.scroll,X=a.style.Cf;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},be=(a,b,c)=>{a.style.paddingLeft=
a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},ce=a=>0>Vd.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},de=(a,b)=>{if(0!=b.pg||0!=b.cg){ae(a);var c=b.th?innerWidth:screen.width,d=b.th?innerHeight:screen.height,e=ce(a),f=e.width;e=e.height;var g=Yd(a),l=g[0];g=g[1];3==b.pg?(be(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.pg&&(c*g<l*d?(f=g*c/l,be(a,(d-f)/2,0),d=f):(f=l*d/g,be(a,0,(c-f)/2),c=f));var n;(n=a.style).backgroundColor||(n.backgroundColor="black");let p;(p=document.body.style).backgroundColor||
(p.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.dh&&(a.style.Cf="optimizeSpeed",a.style.Cf="-moz-crisp-edges",a.style.Cf="-o-crisp-edges",a.style.Cf="-webkit-optimize-contrast",a.style.Cf="optimize-contrast",a.style.Cf="crisp-edges",a.style.Cf="pixelated");n=2==b.cg?devicePixelRatio:1;0!=b.cg&&(c=c*n|0,d=d*n|0,$d(a,c,d),a.Gf&&a.Gf.zf.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return P.fullscreenEnabled()?-3:-1;Ud=b;b.Of&&T(b.Of,37,0,b.zg);return 0},ee=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},fe=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)m[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
m[a+1104]=b.connected;r[a+1108>>2]=b.index;r[a+8>>2]=b.axes.length;r[a+12>>2]=b.buttons.length;C(b.id,q,a+1112,64);C(b.mapping,q,a+1176,64)},ge=(a,b,c)=>{a=Xa(a);a=Bc[a];if(!a)return 0;var d=a.getContext("2d").getImageData(0,0,a.width,a.height),e=A(a.width*a.height*4);q.set(d.data,e);r[b>>2]=a.width;r[c>>2]=a.height;return e},he=[],ie=(a,b,c,d,e,f,g,l)=>{b=M[b];if(a=L[a](b,c))d=l&&C(a.name,q,l,d),e&&(r[e>>2]=d),f&&(r[f>>2]=a.size),g&&(r[g>>2]=a.type)},je=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=
1;break;case 36344:0!=c&&1!=c&&(O||=1280);return;case 36345:d=0;break;case 34466:var e=L.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=L.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":O||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:O||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||
e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:r[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;case 4:m[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){O||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:O||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;t[b>>2]=c;t[b+4>>2]=(c-t[b>>2])/4294967296;break;
case 0:r[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:m[b]=d?1:0}}else O||=1281},ke=(a,b,c)=>{if(c){a=L.vf.getQueryObjectEXT(cd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d;t[c+4>>2]=(d-t[c>>2])/4294967296}else O||=1281},le=(a,b,c)=>{if(c){a=L.vf.getQueryObjectEXT(cd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;r[c>>2]=d}else O||=1281},me=()=>{var a=Vc(L);return a=a.concat(a.map(b=>"GL_"+b))},ne=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),oe=a=>{var b=a.Mf,c=a.Og,d;if(!b){a.Mf=b={};a.Ng={};var e=
L.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=L.getActiveUniform(a,d);var g=f.name;f=f.size;var l=ne(g);l=0<l?g.slice(0,l):g;var n=a.tg;a.tg+=f;c[l]=[f,n];for(g=0;g<f;++g)b[n]=g,a.Ng[n++]=l}}},U=a=>{var b=L.Ug;if(b){var c=b.Mf[a];"number"==typeof c&&(b.Mf[a]=c=L.getUniformLocation(b,b.Ng[a]+(0<c?`[${c}]`:"")));return c}O||=1282},pe=(a,b,c,d)=>{if(c)if(a=M[a],oe(a),a=L.getUniform(a,U(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<
a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b]}else O||=1281},qe=(a,b,c,d)=>{if(c)if(a=L.getVertexAttrib(a,b),34975==b)r[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:r[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b];break;case 5:r[c+4*b>>2]=Math.fround(a[b])}else O||=1281},re=(a,b,c,d,e)=>{a-=5120;a=1==a?q:4==a?r:6==a?w:5==
a||28922==a?t:na;b=d*((fd||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+ed-1&-ed);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},se=[],te=[],ue=(a,b)=>{if(!P.fullscreenEnabled())return-1;a=Q(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Qd()?de(a,b):b.Yg?(Od(de,1,[a,b]),1):-2:-3:-4},ve=()=>{try{if(navigator.getGamepads)return(P.Sf=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},we=(a,
b)=>{var c={target:Q(2),ff:"beforeunload",mf:b,pf:(d=event)=>{var e=T(b,28,0,a);e&&=e?y(q,e):"";if(e)return d.preventDefault(),d.returnValue=e},lf:!0};return Sd(c)},xe=(a,b,c,d,e,f)=>{P.eg||(P.eg=A(256));a={target:Q(a),ff:f,mf:d,pf:(g=event)=>{var l=g.target.id?g.target.id:"",n=P.eg;C(Td(g.target),q,n+0,128);C(l,q,n+128,128);T(d,e,n,b)&&g.preventDefault()},lf:c};return Sd(a)},ye=(a,b,c,d,e)=>{P.gg||(P.gg=A(276));return Sd({target:a,ff:e,mf:d,pf:(f=event)=>{var g=P.gg,l=document.fullscreenElement||
document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!l;m[g]=n;m[g+1]=P.fullscreenEnabled();var p=n?l:P.rh,u=p?.id||"";C(Td(p),q,g+2,128);C(u,q,g+130,128);r[g+260>>2]=p?p.clientWidth:0;r[g+264>>2]=p?p.clientHeight:0;r[g+268>>2]=screen.width;r[g+272>>2]=screen.height;n&&(P.rh=l);T(d,19,g,b)&&f.preventDefault()},lf:c})},ze=(a,b,c,d,e)=>{P.hg||(P.hg=A(1240));b={target:Q(2),Nf:!0,ff:e,mf:c,pf:(f=event)=>{var g=P.hg;fe(g,f.gamepad);T(c,d,g,a)&&f.preventDefault()},
lf:b};return Sd(b)},Be=(a,b,c,d,e,f)=>{P.kg||(P.kg=A(160));a={target:Q(a),ff:f,mf:d,pf:g=>{var l=P.kg;x[l>>3]=g.timeStamp;var n=l>>2;r[n+2]=g.location;m[l+12]=g.ctrlKey;m[l+13]=g.shiftKey;m[l+14]=g.altKey;m[l+15]=g.metaKey;m[l+16]=g.repeat;r[n+5]=g.charCode;r[n+6]=g.keyCode;r[n+7]=g.which;C(g.key||"",q,l+32,32);C(g.code||"",q,l+64,32);C(g.char||"",q,l+96,32);C(g.locale||"",q,l+128,32);T(d,e,l,b)&&g.preventDefault()},lf:c};return Sd(a)},Ce=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;r[d+2]=b.screenX;
r[d+3]=b.screenY;r[d+4]=b.clientX;r[d+5]=b.clientY;m[a+24]=b.ctrlKey;m[a+25]=b.shiftKey;m[a+26]=b.altKey;m[a+27]=b.metaKey;ma[2*d+14]=b.button;ma[2*d+15]=b.buttons;r[d+8]=b.movementX;r[d+9]=b.movementY;a=ce(c);r[d+10]=b.clientX-(a.left|0);r[d+11]=b.clientY-(a.top|0)},De=(a,b,c,d,e,f)=>{P.Xf||(P.Xf=A(64));a=Q(a);return Sd({target:a,Nf:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,ff:f,mf:d,pf:(g=event)=>{Ce(P.Xf,g,a);T(d,e,P.Xf,b)&&g.preventDefault()},lf:c})},Ee=(a,b,c,d,e)=>{P.mg||(P.mg=A(257));
return Sd({target:a,ff:e,mf:d,pf:(f=event)=>{var g=P.mg,l=document.pointerLockElement||document.hf||document.Pg||document.bg;m[g]=!!l;var n=l?.id||"";C(Td(l),q,g+1,128);C(n,q,g+129,128);T(d,20,g,b)&&f.preventDefault()},lf:c})},Fe=(a,b,c,d)=>{P.sg||(P.sg=A(36));a=Q(a);return Sd({target:a,ff:"resize",mf:d,pf:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=P.sg;r[g>>2]=0;r[g+4>>2]=f.clientWidth;r[g+8>>2]=f.clientHeight;r[g+12>>2]=innerWidth;r[g+16>>2]=innerHeight;r[g+20>>2]=outerWidth;r[g+
24>>2]=outerHeight;r[g+28>>2]=pageXOffset|0;r[g+32>>2]=pageYOffset|0;T(d,10,g,b)&&e.preventDefault()}}},lf:c})},Ge=(a,b,c,d,e,f)=>{P.rg||(P.rg=A(1552));a=Q(a);return Sd({target:a,Nf:"touchstart"==f||"touchend"==f,ff:f,mf:d,pf:g=>{var l={},n=g.touches;for(var p of n)p.Eg=p.Jg=0,l[p.identifier]=p;for(var u of g.changedTouches)u.Eg=1,l[u.identifier]=u;for(var v of g.targetTouches)l[v.identifier].Jg=1;n=P.rg;x[n>>3]=g.timeStamp;m[n+12]=g.ctrlKey;m[n+13]=g.shiftKey;m[n+14]=g.altKey;m[n+15]=g.metaKey;p=
n+16;u=ce(a);v=0;for(let z of Object.values(l))if(l=p>>2,r[l]=z.identifier,r[l+1]=z.screenX,r[l+2]=z.screenY,r[l+3]=z.clientX,r[l+4]=z.clientY,r[l+5]=z.pageX,r[l+6]=z.pageY,m[p+28]=z.Eg,m[p+29]=z.Jg,r[l+8]=z.clientX-(u.left|0),r[l+9]=z.clientY-(u.top|0),p+=48,31<++v)break;r[n+8>>2]=v;T(d,e,n,b)&&g.preventDefault()},lf:c})},He=(a,b,c)=>{var d=Vd[1];P.ug||(P.ug=A(8));return Sd({target:d,ff:"visibilitychange",mf:c,pf:(e=event)=>{var f=P.ug,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);
m[f]=document.hidden;r[f+4>>2]=g;T(c,21,f,a)&&e.preventDefault()},lf:b})},Ie=(a,b,c,d)=>{P.vg||(P.vg=A(96));return Sd({target:a,Nf:!0,ff:"wheel",mf:d,pf:(e=event)=>{var f=P.vg;Ce(f,e,a);x[f+64>>3]=e.deltaX;x[f+72>>3]=e.deltaY;x[f+80>>3]=e.deltaZ;r[f+88>>2]=e.deltaMode;T(d,9,f,b)&&e.preventDefault()},lf:c})},Je={},Le=()=>{if(!Ke){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-",
"_")+".UTF-8",_:da||"./this.program"},b;for(b in Je)void 0===Je[b]?delete a[b]:a[b]=Je[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ke=c}return Ke},Ke,Me=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Ja=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Me(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Ka=(a,b=[])=>{var c="vi".replace(/p/g,"i");(0,h["dynCall_"+c])(a,...b)},Ne=a=>{try{a()}catch(b){za(b)}};
function Oe(){var a=V,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...e)=>{Pe.push(c);try{return d(...e)}finally{ka||(Pe.pop(),Qe&&1===Re&&0===Pe.length&&(Re=0,Ne(Se),"undefined"!=typeof Fibers&&Fibers.Wh()))}}:d;return b}var Re=0,Qe=null,Te=0,Pe=[],Ue={},Ve={},We=0,Xe=null,Ye=[];function Ze(){var a=A(4108),b=a+12;t[a>>2]=b;t[a+4>>2]=b+4096;b=Pe[0];var c=Ue[b];void 0===c&&(c=We++,Ue[b]=c,Ve[c]=b);r[a+8>>2]=c;return a}
function $e(a){if(!ka){if(0===Re){var b=!1,c=!1;a((d=0)=>{if(!ka&&(Te=d,b=!0,c)){Re=2;Ne(()=>af(Qe));"undefined"!=typeof wd&&rd&&Gd();d=!1;try{var e=(0,V[Ve[r[Qe+8>>2]]])()}catch(l){e=l,d=!0}var f=!1;if(!Qe){var g=Xe;g&&(Xe=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(Re=1,Qe=Ze(),"undefined"!=typeof wd&&rd&&Fd(),Ne(()=>bf(Qe)))}else 2===Re?(Re=0,Ne(cf),df(Qe),Qe=null,Ye.forEach(wc)):za(`invalid state: ${Re}`);return Te}}
var Ia=0,Ga=(a,b)=>{b=1==b?Wd(a.length):A(a.length);a.subarray||a.slice||(a=new Uint8Array(a));q.set(a,b);return b};Ab=Array(4096);Ub(E,"/");Xb("/tmp");Xb("/home");Xb("/home/web_user");(function(){Xb("/dev");db(259,{read:()=>0,write:(d,e,f,g)=>g,sf:()=>0});Yb("/dev/null",259);cb(1280,fb);cb(1536,gb);Yb("/dev/tty",1280);Yb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Va(a),b=a.byteLength);return a[--b]};jc("/dev","random",c);jc("/dev","urandom",c);Xb("/dev/shm");Xb("/dev/shm/tmp")})();
(function(){Xb("/proc");var a=Xb("/proc/self");Xb("/proc/self/fd");Ub({xf(){var b=lb(a,"fd",16895,73);b.$e={sf:E.$e.sf};b.af={If(c,d){c=+d;var e=Rb(c);c={parent:null,xf:{Ig:"fake"},af:{Lf:()=>e.path},id:c+1};return c.parent=c},og(){return Array.from(yb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.FS_createPath=hc;h.FS_createDataFile=tb;h.FS_createPreloadedFile=ub;h.FS_unlink=ac;h.FS_createLazyFile=lc;h.FS_createDevice=jc;E.Bg=new D(44);E.Bg.stack="<generic error, no stack>";
h.requestFullscreen=function(a,b){function c(){yc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Ic,Gc&&d.requestPointerLock(),yc=!0,Hc?("undefined"!=typeof SDL&&(r[SDL.screen>>2]=t[SDL.screen>>2]|8388608),Lc(h.canvas),Kc()):Lc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Hc?("undefined"!=typeof SDL&&(r[SDL.screen>>2]=
t[SDL.screen>>2]&-8388609),Lc(h.canvas),Kc()):Lc(d));h.onFullScreen?.(yc);h.onFullscreen?.(yc)}Gc=a;Hc=b;"undefined"==typeof Gc&&(Gc=!0);"undefined"==typeof Hc&&(Hc=!1);var d=h.canvas;Fc||(Fc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.setCanvasSize=function(a,b,c){Lc(h.canvas,a,b);c||Kc()};h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
h.createContext=function(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var f={antialias:!1,alpha:!1,Hg:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof od&&(e=kd(a,f)))var l=bd[e].zf}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&nd(e),Ac.forEach(n=>n()),rb());return l};h.requestAnimationFrame=Jd;h.pauseMainLoop=Fd;h.resumeMainLoop=Gd;h.preMainLoop&&Cd.push(h.preMainLoop);h.postMainLoop&&Dd.push(h.postMainLoop);for(var W=0;32>W;++W)he.push(Array(W));var ef=new Float32Array(288);
for(W=0;288>=W;++W)se[W]=ef.subarray(0,W);var ff=new Int32Array(288);for(W=0;288>=W;++W)te[W]=ff.subarray(0,W);
var vf={_a:(a,b)=>dynCall_vi(a,b),vb:function(a){try{a=a?y(q,a):"";var b=Jb(a,{Hf:!0});if(null===b.node)throw new D(44);if(!G(b.node.mode))throw new D(54);var c=Mb(b.node,"x");if(c)throw new D(c);Wa=b.path;return 0}catch(d){if("undefined"==typeof I||"ErrnoError"!==d.name)throw d;return-d.ef}},T:function(a,b,c){oc=c;try{var d=Rb(a);switch(b){case 0:var e=pc();if(0>e)break;for(;yb[e];)e++;return Tb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=pc(),d.flags|=e,0;case 12:return e=
pc(),ma[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof I||"ErrnoError"!==f.name)throw f;return-f.ef}},qb:function(a,b){try{var c=Rb(a);return nc(b,bc(c.path))}catch(d){if("undefined"==typeof I||"ErrnoError"!==d.name)throw d;return-d.ef}},tb:function(a,b,c){oc=c;try{var d=Rb(a);switch(b){case 21509:return d.bf?0:-59;case 21505:if(!d.bf)return-59;if(d.bf.yf.kh){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=pc();r[e>>2]=25856;r[e+
4>>2]=5;r[e+8>>2]=191;r[e+12>>2]=35387;for(var f=0;32>f;f++)m[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.bf?0:-59;case 21506:case 21507:case 21508:if(!d.bf)return-59;if(d.bf.yf.lh)for(e=pc(),a=[],f=0;32>f;f++)a.push(m[e+f+17]);return 0;case 21519:if(!d.bf)return-59;e=pc();return r[e>>2]=0;case 21520:return d.bf?-28:-59;case 21531:e=pc();if(!d.$e.jh)throw new D(59);return d.$e.jh(d,b,e);case 21523:if(!d.bf)return-59;d.bf.yf.mh&&(f=[24,80],e=pc(),ma[e>>1]=f[0],ma[e+2>>1]=f[1]);
return 0;case 21524:return d.bf?0:-59;case 21515:return d.bf?0:-59;default:return-28}}catch(g){if("undefined"==typeof I||"ErrnoError"!==g.name)throw g;return-g.ef}},ob:function(a,b){try{return a=a?y(q,a):"",nc(b,bc(a,!0))}catch(c){if("undefined"==typeof I||"ErrnoError"!==c.name)throw c;return-c.ef}},ib:function(a,b,c){try{return b=b?y(q,b):"",b=mc(a,b),Xb(b,c),0}catch(d){if("undefined"==typeof I||"ErrnoError"!==d.name)throw d;return-d.ef}},nb:function(a,b,c,d){try{b=b?y(q,b):"";var e=d&256;b=mc(a,
b,d&4096);return nc(c,e?bc(b,!0):bc(b))}catch(f){if("undefined"==typeof I||"ErrnoError"!==f.name)throw f;return-f.ef}},V:function(a,b,c,d){oc=d;try{b=b?y(q,b):"";b=mc(a,b);var e=d?pc():0;return dc(b,c,e).fd}catch(f){if("undefined"==typeof I||"ErrnoError"!==f.name)throw f;return-f.ef}},eb:function(a){try{return a=a?y(q,a):"",$b(a),0}catch(b){if("undefined"==typeof I||"ErrnoError"!==b.name)throw b;return-b.ef}},pb:function(a,b){try{return a=a?y(q,a):"",nc(b,bc(a))}catch(c){if("undefined"==typeof I||
"ErrnoError"!==c.name)throw c;return-c.ef}},fb:function(a,b,c){try{return b=b?y(q,b):"",b=mc(a,b),0===c?ac(b):512===c?$b(b):za("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof I||"ErrnoError"!==d.name)throw d;return-d.ef}},wb:()=>za(""),ab:()=>{Pa=!1;qc=0},Za:()=>{throw Infinity;},gb:function(a,b,c,d,e,f,g){e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{if(isNaN(e))return 61;var l=Rb(d);if(0!==(b&2)&&0===(c&2)&&2!==(l.flags&2097155))throw new D(2);if(1===(l.flags&
2097155))throw new D(2);if(!l.$e.Jf)throw new D(43);if(!a)throw new D(28);var n=l.$e.Jf(l,a,e,b,c);var p=n.Lg;r[f>>2]=n.xg;t[g>>2]=p;return 0}catch(u){if("undefined"==typeof I||"ErrnoError"!==u.name)throw u;return-u.ef}},hb:function(a,b,c,d,e,f){f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=Rb(e);if(c&2){if(32768!==(g.node.mode&61440))throw new D(43);d&2||g.$e.Yf&&g.$e.Yf(g,q.slice(a,a+b),f,b,d)}}catch(l){if("undefined"==typeof I||"ErrnoError"!==l.name)throw l;return-l.ef}},cb:(a,
b)=>{rc[a]&&(clearTimeout(rc[a].id),delete rc[a]);if(!b)return 0;var c=setTimeout(()=>{delete rc[a];wc(()=>gf(a,performance.now()))},b);rc[a]={id:c,Vh:b};return 0},Ta:a=>{if(12448==a)return J=12288,1;J=12300;return 0},uc:(a,b,c,d,e)=>{if(62E3!=a)J=12296,c=0;else{if(b)for(;;){a=r[b>>2];if(12321==a)K.alpha=0<r[b+4>>2];else if(12325==a)K.depth=0<r[b+4>>2];else if(12326==a)K.stencil=0<r[b+4>>2];else if(12337==a)a=r[b+4>>2],K.antialias=0<a;else if(12338==a)a=r[b+4>>2],K.antialias=1==a;else if(12544==a)K.Oh=
12547!=r[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(r[e>>2]=1),c&&0<d&&(t[c>>2]=62002),J=12288,c=1):(J=12300,c=0)}return c},Zb:(a,b,c,d)=>{if(62E3!=a)return J=12296,0;for(a=1;;){b=r[d>>2];if(12440==b)a=r[d+4>>2];else if(12344==b)break;else return J=12292,0;d+=8}if(2!=a)return J=12293,0;K.Hg=a-1;K.Qh=0;Rc=kd(h.canvas,K);if(0!=Rc)return J=12288,nd(Rc),Ac.forEach(e=>e()),nd(null),62004;J=12297;return 0},Db:(a,b)=>{if(62E3!=a)return J=12296,0;if(62002!=b)return J=12293,0;J=12288;return 62006},Ob:(a,
b)=>{if(62E3!=a)return J=12296,0;if(62004!=b)return J=12294,0;a=Rc;md===bd[a]&&(md=null);"object"==typeof P&&P.sh(bd[a].zf.canvas);bd[a]&&bd[a].zf.canvas&&(bd[a].zf.canvas.Gf=void 0);bd[a]=null;J=12288;Nc==b&&(Nc=0);return 1},ub:(a,b)=>{if(62E3!=a)return J=12296,0;if(62006!=b)return J=12301,1;Oc==b&&(Oc=0);Pc==b&&(Pc=0);J=12288;return 1},jc:(a,b,c,d)=>{if(62E3!=a)return J=12296,0;if(62002!=b)return J=12293,0;if(!d)return J=12300,0;J=12288;switch(c){case 12320:return r[d>>2]=K.alpha?32:24,1;case 12321:return r[d>>
2]=K.alpha?8:0,1;case 12322:return r[d>>2]=8,1;case 12323:return r[d>>2]=8,1;case 12324:return r[d>>2]=8,1;case 12325:return r[d>>2]=K.depth?24:0,1;case 12326:return r[d>>2]=K.stencil?8:0,1;case 12327:return r[d>>2]=12344,1;case 12328:return r[d>>2]=62002,1;case 12329:return r[d>>2]=0,1;case 12330:return r[d>>2]=4096,1;case 12331:return r[d>>2]=16777216,1;case 12332:return r[d>>2]=4096,1;case 12333:return r[d>>2]=0,1;case 12334:return r[d>>2]=0,1;case 12335:return r[d>>2]=12344,1;case 12337:return r[d>>
2]=K.antialias?4:0,1;case 12338:return r[d>>2]=K.antialias?1:0,1;case 12339:return r[d>>2]=4,1;case 12340:return r[d>>2]=12344,1;case 12341:case 12342:case 12343:return r[d>>2]=-1,1;case 12345:case 12346:return r[d>>2]=0,1;case 12347:return r[d>>2]=0,1;case 12348:return r[d>>2]=1;case 12349:case 12350:return r[d>>2]=0,1;case 12351:return r[d>>2]=12430,1;case 12352:return r[d>>2]=4,1;case 12354:return r[d>>2]=0,1;default:return J=12292,0}},W:a=>{J=12288;return 0!=a&&1!=a?0:62E3},Qa:()=>J,Qc:(a,b,c)=>
{if(62E3!=a)return J=12296,0;b&&(r[b>>2]=1);c&&(r[c>>2]=4);Mc=!0;J=12288;return 1},lb:(a,b,c,d)=>{if(62E3!=a)return J=12296,0;if(0!=d&&62004!=d)return J=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return J=12301,0;nd(d?Rc:null);Nc=d;Pc=b;Oc=c;J=12288;return 1},Ra:(a,b)=>{if(62E3!=a)return J=12296,0;J=12288;if(Qc[b])return Qc[b];switch(b){case 12371:a=pd("Emscripten");break;case 12372:a=pd("1.4 Emscripten EGL");break;case 12373:a=pd("");break;case 12429:a=pd("OpenGL_ES");break;default:return J=12300,
0}return Qc[b]=a},bb:()=>{if(Mc)if(L)if(L.isContextLost())J=12302;else return J=12288,1;else J=12290;else J=12289;return 0},Ya:(a,b)=>{if(62E3!=a)return J=12296,0;0==b?Hd(0,0):Hd(1,b);J=12288;return 1},Fc:a=>{if(62E3!=a)return J=12296,0;Pc=Oc=Nc=0;Mc=!1;J=12288;return 1},Ua:()=>{J=12288;return 1},Va:()=>{J=12288;return 1},Ba:(a,b,c)=>{b=Md(b,c);return Ma[a](...b)},c:(a,b,c)=>{b=Md(b,c);return Ma[a](...b)},D:(a,b,c)=>{b=Md(b,c);return Ma[a](...b)},Sa:()=>{Fd();rd=null},U:()=>Date.now(),Ka:()=>{if(!P.fullscreenEnabled())return-1;
Pd(de);var a=Vd[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Oa:()=>{Pd(ee);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},Na:a=>{Pa=!1;qc=0;la=a;tc(a)},j:()=>devicePixelRatio,g:(a,b,c)=>{a=Q(a);if(!a)return-4;a=ce(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},X:(a,b)=>{if(0>a||a>=P.Sf.length)return-5;if(!P.Sf[a])return-7;fe(b,P.Sf[a]);return 0},
p:()=>performance.now(),ga:()=>P.Sf.length,Xd:(a,b,c)=>ge(a?y(q,a):"",b,c),_b:(a,b,c)=>{a=hf(a);return(a=yb[a])?ge(a.path,b,c):0},Pa:(a,b)=>{r[a>>2]=screen.width;r[b>>2]=screen.height},pa:a=>L.activeTexture(a),oa:(a,b)=>{L.attachShader(M[a],N[b])},Ga:(a,b)=>{L.vf.beginQueryEXT(a,cd[b])},na:(a,b,c)=>{L.bindAttribLocation(M[a],b,c?y(q,c):"")},ma:(a,b)=>{L.bindBuffer(a,Xc[b])},la:(a,b)=>{L.bindFramebuffer(a,Yc[b])},ka:(a,b)=>{L.bindRenderbuffer(a,Zc[b])},ja:(a,b)=>{L.bindTexture(a,$c[b])},xa:a=>{L.bindVertexArray(ad[a])},
ia:(a,b,c,d)=>L.blendColor(a,b,c,d),ha:a=>L.blendEquation(a),fa:(a,b)=>L.blendEquationSeparate(a,b),ea:(a,b)=>L.blendFunc(a,b),da:(a,b,c,d)=>L.blendFuncSeparate(a,b,c,d),ca:(a,b,c,d)=>{L.bufferData(a,c?q.subarray(c,c+b):b,d)},ba:(a,b,c,d)=>{L.bufferSubData(a,b,q.subarray(d,d+c))},aa:a=>L.checkFramebufferStatus(a),$:a=>L.clear(a),_:(a,b,c,d)=>L.clearColor(a,b,c,d),Z:a=>L.clearDepth(a),Y:a=>L.clearStencil(a),yb:(a,b)=>{L.ah.clipControlEXT(a,b)},Wd:(a,b,c,d)=>{L.colorMask(!!a,!!b,!!c,!!d)},Vd:a=>{L.compileShader(N[a])},
Ud:(a,b,c,d,e,f,g,l)=>{L.compressedTexImage2D(a,b,c,d,e,f,q.subarray(l,l+g))},Td:(a,b,c,d,e,f,g,l,n)=>{L.compressedTexSubImage2D(a,b,c,d,e,f,g,q.subarray(n,n+l))},Sd:(a,b,c,d,e,f,g,l)=>L.copyTexImage2D(a,b,c,d,e,f,g,l),Rd:(a,b,c,d,e,f,g,l)=>L.copyTexSubImage2D(a,b,c,d,e,f,g,l),Qd:()=>{var a=gd(M),b=L.createProgram();b.name=a;b.Vf=b.Tf=b.Uf=0;b.tg=1;M[a]=b;return a},Pd:a=>{var b=gd(N);N[b]=L.createShader(a);return b},Od:a=>L.cullFace(a),Nd:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Xc[d];e&&
(L.deleteBuffer(e),e.name=0,Xc[d]=null)}},Md:(a,b)=>{for(var c=0;c<a;++c){var d=r[b+4*c>>2],e=Yc[d];e&&(L.deleteFramebuffer(e),e.name=0,Yc[d]=null)}},Ld:a=>{if(a){var b=M[a];b?(L.deleteProgram(b),b.name=0,M[a]=null):O||=1281}},Ia:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=cd[d];e&&(L.vf.deleteQueryEXT(e),cd[d]=null)}},Kd:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Zc[d];e&&(L.deleteRenderbuffer(e),e.name=0,Zc[d]=null)}},Jd:a=>{if(a){var b=N[a];b?(L.deleteShader(b),N[a]=null):O||=1281}},
Id:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=$c[d];e&&(L.deleteTexture(e),e.name=0,$c[d]=null)}},wa:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2];L.deleteVertexArray(ad[d]);ad[d]=null}},Hd:a=>L.depthFunc(a),Gd:a=>{L.depthMask(!!a)},Fd:(a,b)=>L.depthRange(a,b),Ed:(a,b)=>{L.detachShader(M[a],N[b])},Dd:a=>L.disable(a),Cd:a=>{L.disableVertexAttribArray(a)},Bd:(a,b,c)=>{L.drawArrays(a,b,c)},sa:(a,b,c,d)=>{L.drawArraysInstanced(a,b,c,d)},ta:(a,b)=>{for(var c=he[a],d=0;d<a;d++)c[d]=r[b+4*d>>2];L.drawBuffers(c)},
Ad:(a,b,c,d)=>{L.drawElements(a,b,c,d)},ra:(a,b,c,d,e)=>{L.drawElementsInstanced(a,b,c,d,e)},zd:a=>L.enable(a),yd:a=>{L.enableVertexAttribArray(a)},Fa:a=>{L.vf.endQueryEXT(a)},xd:()=>L.finish(),wd:()=>L.flush(),vd:(a,b,c,d)=>{L.framebufferRenderbuffer(a,b,c,Zc[d])},ud:(a,b,c,d,e)=>{L.framebufferTexture2D(a,b,c,$c[d],e)},td:a=>L.frontFace(a),sd:(a,b)=>{hd(a,b,"createBuffer",Xc)},qd:(a,b)=>{hd(a,b,"createFramebuffer",Yc)},Ja:(a,b)=>{for(var c=0;c<a;c++){var d=L.vf.createQueryEXT();if(!d){for(O||=1282;c<
a;)r[b+4*c++>>2]=0;break}var e=gd(cd);d.name=e;cd[e]=d;r[b+4*c>>2]=e}},pd:(a,b)=>{hd(a,b,"createRenderbuffer",Zc)},od:(a,b)=>{hd(a,b,"createTexture",$c)},va:(a,b)=>{hd(a,b,"createVertexArray",ad)},rd:a=>L.generateMipmap(a),nd:(a,b,c,d,e,f,g)=>ie("getActiveAttrib",a,b,c,d,e,f,g),md:(a,b,c,d,e,f,g)=>ie("getActiveUniform",a,b,c,d,e,f,g),ld:(a,b,c,d)=>{a=L.getAttachedShaders(M[a]);var e=a.length;e>b&&(e=b);r[c>>2]=e;for(b=0;b<e;++b)r[d+4*b>>2]=N.indexOf(a[b])},kd:(a,b)=>L.getAttribLocation(M[a],b?y(q,
b):""),jd:(a,b)=>je(a,b,4),id:(a,b,c)=>{c?r[c>>2]=L.getBufferParameter(a,b):O||=1281},hd:()=>{var a=L.getError()||O;O=0;return a},gd:(a,b)=>je(a,b,2),fd:(a,b,c,d)=>{a=L.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;r[d>>2]=a},ed:(a,b)=>je(a,b,0),cd:(a,b,c,d)=>{a=L.getProgramInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,q,d,b):0;c&&(r[c>>2]=b)},dd:(a,b,c)=>{if(c)if(a>=Wc)O||=1281;else if(a=M[a],35716==b)a=L.getProgramInfoLog(a),
null===a&&(a="(unknown error)"),r[c>>2]=a.length+1;else if(35719==b){if(!a.Vf){var d=L.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Vf=Math.max(a.Vf,L.getActiveUniform(a,b).name.length+1)}r[c>>2]=a.Vf}else if(35722==b){if(!a.Tf)for(d=L.getProgramParameter(a,35721),b=0;b<d;++b)a.Tf=Math.max(a.Tf,L.getActiveAttrib(a,b).name.length+1);r[c>>2]=a.Tf}else if(35381==b){if(!a.Uf)for(d=L.getProgramParameter(a,35382),b=0;b<d;++b)a.Uf=Math.max(a.Uf,L.getActiveUniformBlockName(a,b).length+1);r[c>>2]=a.Uf}else r[c>>
2]=L.getProgramParameter(a,b);else O||=1281},za:ke,Ca:le,ya:ke,Aa:le,Da:(a,b,c)=>{c?r[c>>2]=L.vf.getQueryEXT(a,b):O||=1281},bd:(a,b,c)=>{c?r[c>>2]=L.getRenderbufferParameter(a,b):O||=1281},$c:(a,b,c,d)=>{a=L.getShaderInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,q,d,b):0;c&&(r[c>>2]=b)},_c:(a,b,c,d)=>{a=L.getShaderPrecisionFormat(a,b);r[c>>2]=a.rangeMin;r[c+4>>2]=a.rangeMax;r[d>>2]=a.precision},Zc:(a,b,c,d)=>{if(a=L.getShaderSource(N[a]))b=0<b&&d?C(a,q,d,b):0,c&&(r[c>>2]=b)},ad:(a,b,
c)=>{c?35716==b?(a=L.getShaderInfoLog(N[a]),null===a&&(a="(unknown error)"),r[c>>2]=a?a.length+1:0):35720==b?(a=L.getShaderSource(N[a]),r[c>>2]=a?a.length+1:0):r[c>>2]=L.getShaderParameter(N[a],b):O||=1281},Yc:a=>{var b=dd[a];if(!b){switch(a){case 7939:b=pd(me().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=L.getParameter(a))||(O||=1280);b=b?pd(b):0;break;case 7938:b=pd(`OpenGL ES 2.0 (${L.getParameter(7938)})`);break;case 35724:b=L.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=pd(b);break;default:O||=1280}dd[a]=b}return b},Xc:(a,b,c)=>{c?w[c>>2]=L.getTexParameter(a,b):O||=1281},Wc:(a,b,c)=>{c?r[c>>2]=L.getTexParameter(a,b):O||=1281},Tc:(a,b)=>{b=b?y(q,b):"";if(a=M[a]){oe(a);var c=a.Mf,d=0,e=b,f=ne(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Og[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||L.getUniformLocation(a,b)))return d}else O||=1281;return-1},Vc:(a,b,c)=>{pe(a,b,c,2)},Uc:(a,b,c)=>{pe(a,
b,c,0)},Pc:(a,b,c)=>{c?r[c>>2]=L.getVertexAttribOffset(a,b):O||=1281},Sc:(a,b,c)=>{qe(a,b,c,2)},Rc:(a,b,c)=>{qe(a,b,c,5)},Oc:(a,b)=>L.hint(a,b),Nc:a=>(a=Xc[a])?L.isBuffer(a):0,Mc:a=>L.isEnabled(a),Lc:a=>(a=Yc[a])?L.isFramebuffer(a):0,Kc:a=>(a=M[a])?L.isProgram(a):0,Ha:a=>(a=cd[a])?L.vf.isQueryEXT(a):0,Jc:a=>(a=Zc[a])?L.isRenderbuffer(a):0,Ic:a=>(a=N[a])?L.isShader(a):0,Hc:a=>(a=$c[a])?L.isTexture(a):0,ua:a=>(a=ad[a])?L.isVertexArray(a):0,Gc:a=>L.lineWidth(a),Ec:a=>{a=M[a];L.linkProgram(a);a.Mf=0;
a.Og={}},Dc:(a,b)=>{3317==a?ed=b:3314==a&&(fd=b);L.pixelStorei(a,b)},xb:(a,b)=>{L.vh.polygonModeWEBGL(a,b)},Cc:(a,b)=>L.polygonOffset(a,b),zb:(a,b,c)=>{L.bh.polygonOffsetClampEXT(a,b,c)},Ea:(a,b)=>{L.vf.queryCounterEXT(cd[a],b)},Bc:(a,b,c,d,e,f,g)=>{(g=re(f,e,c,d,g))?L.readPixels(a,b,c,d,e,f,g):O||=1280},Ac:()=>{},zc:(a,b,c,d)=>L.renderbufferStorage(a,b,c,d),yc:(a,b)=>{L.sampleCoverage(a,!!b)},xc:(a,b,c,d)=>L.scissor(a,b,c,d),wc:()=>{O||=1280},vc:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=t[c+
4*f>>2])?y(q,g,d?t[d+4*f>>2]:void 0):"";e+=g}L.shaderSource(N[a],e)},tc:(a,b,c)=>L.stencilFunc(a,b,c),sc:(a,b,c,d)=>L.stencilFuncSeparate(a,b,c,d),rc:a=>L.stencilMask(a),qc:(a,b)=>L.stencilMaskSeparate(a,b),pc:(a,b,c)=>L.stencilOp(a,b,c),oc:(a,b,c,d)=>L.stencilOpSeparate(a,b,c,d),nc:(a,b,c,d,e,f,g,l,n)=>{n=n?re(l,g,d,e,n):null;L.texImage2D(a,b,c,d,e,f,g,l,n)},mc:(a,b,c)=>L.texParameterf(a,b,c),lc:(a,b,c)=>{L.texParameterf(a,b,w[c>>2])},kc:(a,b,c)=>L.texParameteri(a,b,c),ic:(a,b,c)=>{L.texParameteri(a,
b,r[c>>2])},hc:(a,b,c,d,e,f,g,l,n)=>{n=n?re(l,g,e,f,n):null;L.texSubImage2D(a,b,c,d,e,f,g,l,n)},gc:(a,b)=>{L.uniform1f(U(a),b)},fc:(a,b,c)=>{if(288>=b)for(var d=se[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);L.uniform1fv(U(a),d)},ec:(a,b)=>{L.uniform1i(U(a),b)},dc:(a,b,c)=>{if(288>=b)for(var d=te[b],e=0;e<b;++e)d[e]=r[c+4*e>>2];else d=r.subarray(c>>2,c+4*b>>2);L.uniform1iv(U(a),d)},cc:(a,b,c)=>{L.uniform2f(U(a),b,c)},bc:(a,b,c)=>{if(144>=b){b*=2;for(var d=se[b],e=0;e<b;e+=2)d[e]=
w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);L.uniform2fv(U(a),d)},ac:(a,b,c)=>{L.uniform2i(U(a),b,c)},$b:(a,b,c)=>{if(144>=b){b*=2;for(var d=te[b],e=0;e<b;e+=2)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2]}else d=r.subarray(c>>2,c+8*b>>2);L.uniform2iv(U(a),d)},Yb:(a,b,c,d)=>{L.uniform3f(U(a),b,c,d)},Xb:(a,b,c)=>{if(96>=b){b*=3;for(var d=se[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);L.uniform3fv(U(a),d)},Wb:(a,
b,c,d)=>{L.uniform3i(U(a),b,c,d)},Vb:(a,b,c)=>{if(96>=b){b*=3;for(var d=te[b],e=0;e<b;e+=3)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2]}else d=r.subarray(c>>2,c+12*b>>2);L.uniform3iv(U(a),d)},Ub:(a,b,c,d,e)=>{L.uniform4f(U(a),b,c,d,e)},Tb:(a,b,c)=>{if(72>=b){var d=se[4*b],e=w;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);L.uniform4fv(U(a),d)},Sb:(a,b,c,d,e)=>{L.uniform4i(U(a),b,c,d,e)},Rb:(a,b,c)=>
{if(72>=b){b*=4;for(var d=te[b],e=0;e<b;e+=4)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2],d[e+3]=r[c+(4*e+12)>>2]}else d=r.subarray(c>>2,c+16*b>>2);L.uniform4iv(U(a),d)},Qb:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=se[b],f=0;f<b;f+=4)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2]}else e=w.subarray(d>>2,d+16*b>>2);L.uniformMatrix2fv(U(a),!!c,e)},Pb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=se[b],f=0;f<b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+
2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2]}else e=w.subarray(d>>2,d+36*b>>2);L.uniformMatrix3fv(U(a),!!c,e)},Nb:(a,b,c,d)=>{if(18>=b){var e=se[16*b],f=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];
e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);L.uniformMatrix4fv(U(a),!!c,e)},Mb:a=>{a=M[a];L.useProgram(a);L.Ug=a},Lb:a=>{L.validateProgram(M[a])},Kb:(a,b)=>L.vertexAttrib1f(a,b),Jb:(a,b)=>{L.vertexAttrib1f(a,w[b>>2])},Ib:(a,b,c)=>L.vertexAttrib2f(a,b,c),Hb:(a,b)=>{L.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},Gb:(a,b,c,d)=>L.vertexAttrib3f(a,b,c,d),Fb:(a,b)=>{L.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},Eb:(a,b,c,d,e)=>L.vertexAttrib4f(a,b,c,d,e),Cb:(a,b)=>{L.vertexAttrib4f(a,
w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},qa:(a,b)=>{L.vertexAttribDivisor(a,b)},Bb:(a,b,c,d,e,f)=>{L.vertexAttribPointer(a,b,c,!!d,e,f)},Ab:(a,b,c,d)=>L.viewport(a,b,c,d),s:()=>1,La:(a,b,c)=>ue(a,{pg:r[c>>2],cg:r[c+4>>2],dh:r[c+8>>2],Yg:b,Of:r[c+12>>2],zg:r[c+16>>2]}),P:(a,b)=>{a=Q(a);return a?a.requestPointerLock?Qd()?ee(a):b?(Od(ee,2,[a]),1):-2:-1:-4},db:()=>{za("OOM")},t:ve,u:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:we(a,b),H:(a,b,c,d)=>xe(a,b,c,d,12,"blur"),i:Zd,n:(a,b,c)=>{a=Q(a);
if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},I:(a,b,c,d)=>xe(a,b,c,d,13,"focus"),x:(a,b,c,d)=>{if(!P.fullscreenEnabled())return-1;a=Q(a);if(!a)return-4;ye(a,b,c,d,"webkitfullscreenchange");return ye(a,b,c,d,"fullscreenchange")},m:(a,b,c)=>ve()?-1:ze(a,b,c,26,"gamepadconnected"),l:(a,b,c)=>ve()?-1:ze(a,b,c,27,"gamepaddisconnected"),A:(a,b,c,d)=>Be(a,b,c,d,2,"keydown"),y:(a,b,c,d)=>Be(a,b,c,d,1,"keypress"),z:(a,b,c,d)=>Be(a,b,c,d,3,"keyup"),N:(a,b,c,d)=>De(a,b,c,d,5,"mousedown"),
L:(a,b,c,d)=>De(a,b,c,d,33,"mouseenter"),K:(a,b,c,d)=>De(a,b,c,d,34,"mouseleave"),O:(a,b,c,d)=>De(a,b,c,d,8,"mousemove"),M:(a,b,c,d)=>De(a,b,c,d,6,"mouseup"),B:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.hf||document.body.Pg||document.body.bg))return-1;a=Q(a);if(!a)return-4;Ee(a,b,c,d,"mozpointerlockchange");Ee(a,b,c,d,"webkitpointerlockchange");Ee(a,b,c,d,"mspointerlockchange");return Ee(a,b,c,d,"pointerlockchange")},w:(a,b,c,d)=>Fe(a,b,c,d),C:(a,b,
c,d)=>Ge(a,b,c,d,25,"touchcancel"),F:(a,b,c,d)=>Ge(a,b,c,d,23,"touchend"),E:(a,b,c,d)=>Ge(a,b,c,d,24,"touchmove"),G:(a,b,c,d)=>Ge(a,b,c,d,22,"touchstart"),v:(a,b,c)=>He(a,b,c),J:(a,b,c,d)=>(a=Q(a))?"undefined"!=typeof a.onwheel?Ie(a,b,c,d):-1:-4,Ma:a=>document.title=a?y(q,a):"",r:a=>$e(b=>xc(b,a)),kb:(a,b)=>{var c=0;Le().forEach((d,e)=>{var f=b+c;e=t[a+4*e>>2]=f;for(f=0;f<d.length;++f)m[e++]=d.charCodeAt(f);m[e]=0;c+=d.length+1});return 0},mb:(a,b)=>{var c=Le();t[a>>2]=c.length;var d=0;c.forEach(e=>
d+=e.length+1);t[b>>2]=d;return 0},e:uc,q:function(a){try{var b=Rb(a);ec(b);return 0}catch(c){if("undefined"==typeof I||"ErrnoError"!==c.name)throw c;return c.ef}},sb:function(a,b,c,d){try{a:{var e=Rb(a);a=b;for(var f,g=b=0;g<c;g++){var l=t[a>>2],n=t[a+4>>2];a+=8;var p=e,u=f,v=m;if(0>n||0>u)throw new D(28);if(null===p.fd)throw new D(8);if(1===(p.flags&2097155))throw new D(8);if(G(p.node.mode))throw new D(31);if(!p.$e.read)throw new D(28);var z="undefined"!=typeof u;if(!z)u=p.position;else if(!p.seekable)throw new D(70);
var B=p.$e.read(p,v,l,n,u);z||(p.position+=B);var F=B;if(0>F){var H=-1;break a}b+=F;if(F<n)break;"undefined"!=typeof f&&(f+=F)}H=b}t[d>>2]=H;return 0}catch(Y){if("undefined"==typeof I||"ErrnoError"!==Y.name)throw Y;return Y.ef}},jb:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Rb(a);fc(e,b,c);oa[d>>3]=BigInt(e.position);e.ig&&0===b&&0===c&&(e.ig=null);return 0}catch(f){if("undefined"==typeof I||"ErrnoError"!==f.name)throw f;return f.ef}},
rb:function(a,b,c,d){try{a:{var e=Rb(a);a=b;for(var f,g=b=0;g<c;g++){var l=t[a>>2],n=t[a+4>>2];a+=8;var p=gc(e,m,l,n,f);if(0>p){var u=-1;break a}b+=p;if(p<n)break;"undefined"!=typeof f&&(f+=p)}u=b}t[d>>2]=u;return 0}catch(v){if("undefined"==typeof I||"ErrnoError"!==v.name)throw v;return v.ef}},h:jf,Wa:kf,b:lf,f:mf,Xa:nf,S:of,Q:pf,k:qf,a:rf,d:sf,o:tf,R:uf,$a:tc},V;
(async function(){function a(c){V=c.exports;V=Oe();ja=V.Yd;c=ja.buffer;h.HEAP8=m=new Int8Array(c);h.HEAP16=ma=new Int16Array(c);h.HEAPU8=q=new Uint8Array(c);h.HEAPU16=na=new Uint16Array(c);h.HEAP32=r=new Int32Array(c);h.HEAPU32=t=new Uint32Array(c);h.HEAPF32=w=new Float32Array(c);h.HEAPF64=x=new Float64Array(c);h.HEAP64=oa=new BigInt64Array(c);h.HEAPU64=new BigUint64Array(c);ra.unshift(V.Zd);ya("wasm-instantiate");return V}xa("wasm-instantiate");var b={a:vf};if(h.instantiateWasm)try{return h.instantiateWasm(b,
a)}catch(c){return k(`Module.instantiateWasm callback failed with error: ${c}`),!1}Aa??=pa("index.wasm")?"index.wasm":h.locateFile?h.locateFile("index.wasm",ea):ea+"index.wasm";return a((await Da(b)).instance)})();
var A=a=>(A=V._d)(a),df=a=>(df=V.$d)(a),wf=h._main=(a,b)=>(wf=h._main=V.ae)(a,b),hf=a=>(hf=V.be)(a),hb=(a,b)=>(hb=V.de)(a,b),gf=(a,b)=>(gf=V.ee)(a,b),Z=(a,b)=>(Z=V.fe)(a,b),S=a=>(S=V.ge)(a),Wd=a=>(Wd=V.he)(a),R=()=>(R=V.ie)(),xf=h.dynCall_viiii=(a,b,c,d,e)=>(xf=h.dynCall_viiii=V.je)(a,b,c,d,e),dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=V.ke)(a,b,c),yf=h.dynCall_ii=(a,b)=>(yf=h.dynCall_ii=V.le)(a,b),zf=h.dynCall_iiiii=(a,b,c,d,e)=>(zf=h.dynCall_iiiii=V.me)(a,b,c,d,e),Af=h.dynCall_jiji=
(a,b,c,d)=>(Af=h.dynCall_jiji=V.ne)(a,b,c,d);h.dynCall_ji=(a,b)=>(h.dynCall_ji=V.oe)(a,b);h.dynCall_viiiii=(a,b,c,d,e,f)=>(h.dynCall_viiiii=V.pe)(a,b,c,d,e,f);
var Bf=h.dynCall_iiiiii=(a,b,c,d,e,f)=>(Bf=h.dynCall_iiiiii=V.qe)(a,b,c,d,e,f),dynCall_iii=h.dynCall_iii=(a,b,c)=>(dynCall_iii=h.dynCall_iii=V.re)(a,b,c),Cf=h.dynCall_viii=(a,b,c,d)=>(Cf=h.dynCall_viii=V.se)(a,b,c,d),dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=h.dynCall_vi=V.te)(a,b),dynCall_v=h.dynCall_v=a=>(dynCall_v=h.dynCall_v=V.ue)(a),T=h.dynCall_iiii=(a,b,c,d)=>(T=h.dynCall_iiii=V.ve)(a,b,c,d);h.dynCall_iiji=(a,b,c,d)=>(h.dynCall_iiji=V.we)(a,b,c,d);
h.dynCall_viiiiiii=(a,b,c,d,e,f,g,l)=>(h.dynCall_viiiiiii=V.xe)(a,b,c,d,e,f,g,l);var Df=h.dynCall_iiiiiii=(a,b,c,d,e,f,g)=>(Df=h.dynCall_iiiiiii=V.ye)(a,b,c,d,e,f,g);h.dynCall_viiiiiiiii=(a,b,c,d,e,f,g,l,n,p)=>(h.dynCall_viiiiiiiii=V.ze)(a,b,c,d,e,f,g,l,n,p);var Ef=h.dynCall_iiiiiiiiii=(a,b,c,d,e,f,g,l,n,p)=>(Ef=h.dynCall_iiiiiiiiii=V.Ae)(a,b,c,d,e,f,g,l,n,p);h.dynCall_iiiiiiii=(a,b,c,d,e,f,g,l)=>(h.dynCall_iiiiiiii=V.Be)(a,b,c,d,e,f,g,l);
h.dynCall_iiiiiiiiiiiiiiff=(a,b,c,d,e,f,g,l,n,p,u,v,z,B,F,H)=>(h.dynCall_iiiiiiiiiiiiiiff=V.Ce)(a,b,c,d,e,f,g,l,n,p,u,v,z,B,F,H);h.dynCall_iiiiiiiii=(a,b,c,d,e,f,g,l,n)=>(h.dynCall_iiiiiiiii=V.De)(a,b,c,d,e,f,g,l,n);h.dynCall_viiiiiiiiiii=(a,b,c,d,e,f,g,l,n,p,u,v)=>(h.dynCall_viiiiiiiiiii=V.Ee)(a,b,c,d,e,f,g,l,n,p,u,v);h.dynCall_iiiiiidiiff=(a,b,c,d,e,f,g,l,n,p,u)=>(h.dynCall_iiiiiidiiff=V.Fe)(a,b,c,d,e,f,g,l,n,p,u);h.dynCall_i=a=>(h.dynCall_i=V.Ge)(a);
h.dynCall_vffff=(a,b,c,d,e)=>(h.dynCall_vffff=V.He)(a,b,c,d,e);h.dynCall_vf=(a,b)=>(h.dynCall_vf=V.Ie)(a,b);h.dynCall_viiiiiiii=(a,b,c,d,e,f,g,l,n)=>(h.dynCall_viiiiiiii=V.Je)(a,b,c,d,e,f,g,l,n);h.dynCall_vff=(a,b,c)=>(h.dynCall_vff=V.Ke)(a,b,c);h.dynCall_vfi=(a,b,c)=>(h.dynCall_vfi=V.Le)(a,b,c);h.dynCall_viif=(a,b,c,d)=>(h.dynCall_viif=V.Me)(a,b,c,d);h.dynCall_vif=(a,b,c)=>(h.dynCall_vif=V.Ne)(a,b,c);h.dynCall_viff=(a,b,c,d)=>(h.dynCall_viff=V.Oe)(a,b,c,d);
h.dynCall_vifff=(a,b,c,d,e)=>(h.dynCall_vifff=V.Pe)(a,b,c,d,e);h.dynCall_viffff=(a,b,c,d,e,f)=>(h.dynCall_viffff=V.Qe)(a,b,c,d,e,f);h.dynCall_viiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_viiiiii=V.Re)(a,b,c,d,e,f,g);h.dynCall_vfff=(a,b,c,d)=>(h.dynCall_vfff=V.Se)(a,b,c,d);h.dynCall_iidiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iidiiii=V.Te)(a,b,c,d,e,f,g);h.dynCall_iid=(a,b,c)=>(h.dynCall_iid=V.Ue)(a,b,c);h.dynCall_di=(a,b)=>(h.dynCall_di=V.Ve)(a,b);h.dynCall_fi=(a,b)=>(h.dynCall_fi=V.We)(a,b);
var bf=a=>(bf=V.Xe)(a),Se=()=>(Se=V.Ye)(),af=a=>(af=V.Ze)(a),cf=()=>(cf=V._e)();function qf(a,b,c,d){var e=R();try{return Af(a,b,c,d)}catch(f){S(e);if(f!==f+0)throw f;Z(1,0);return 0n}}function rf(a,b){var c=R();try{dynCall_vi(a,b)}catch(d){S(c);if(d!==d+0)throw d;Z(1,0)}}function sf(a,b,c){var d=R();try{dynCall_vii(a,b,c)}catch(e){S(d);if(e!==e+0)throw e;Z(1,0)}}function lf(a,b,c,d){var e=R();try{return T(a,b,c,d)}catch(f){S(e);if(f!==f+0)throw f;Z(1,0)}}
function jf(a,b){var c=R();try{return yf(a,b)}catch(d){S(c);if(d!==d+0)throw d;Z(1,0)}}function mf(a,b,c,d,e){var f=R();try{return zf(a,b,c,d,e)}catch(g){S(f);if(g!==g+0)throw g;Z(1,0)}}function of(a,b,c,d,e,f,g){var l=R();try{return Df(a,b,c,d,e,f,g)}catch(n){S(l);if(n!==n+0)throw n;Z(1,0)}}function uf(a,b,c,d,e){var f=R();try{xf(a,b,c,d,e)}catch(g){S(f);if(g!==g+0)throw g;Z(1,0)}}function tf(a,b,c,d){var e=R();try{Cf(a,b,c,d)}catch(f){S(e);if(f!==f+0)throw f;Z(1,0)}}
function pf(a,b,c,d,e,f,g,l,n,p){var u=R();try{return Ef(a,b,c,d,e,f,g,l,n,p)}catch(v){S(u);if(v!==v+0)throw v;Z(1,0)}}function nf(a,b,c,d,e,f){var g=R();try{return Bf(a,b,c,d,e,f)}catch(l){S(g);if(l!==l+0)throw l;Z(1,0)}}function kf(a,b,c){var d=R();try{return dynCall_iii(a,b,c)}catch(e){S(d);if(e!==e+0)throw e;Z(1,0)}}h.addRunDependency=xa;h.removeRunDependency=ya;h.FS_createPreloadedFile=ub;h.FS_unlink=a=>ac(a);h.FS_createPath=hc;h.FS_createDevice=jc;
h.FS_createDataFile=(a,b,c,d,e,f)=>{tb(a,b,c,d,e,f)};h.FS_createLazyFile=lc;h.allocate=Ga;function Ff(a=[]){var b=wf;a.unshift(da);var c=a.length,d=Wd(4*(c+1)),e=d;a.forEach(g=>{t[e>>2]=Xd(g);e+=4});t[e>>2]=0;try{var f=b(c,d);uc(f,!0)}catch(g){sc(g)}}
function Gf(a=ca){function b(){h.calledRun=!0;if(!ka){if(!h.noFSInit&&!Bb){var c,d;Bb=!0;e??=h.stdin;c??=h.stdout;d??=h.stderr;e?jc("/dev","stdin",e):Zb("/dev/tty","/dev/stdin");c?jc("/dev","stdout",null,c):Zb("/dev/tty","/dev/stdout");d?jc("/dev","stderr",null,d):Zb("/dev/tty1","/dev/stderr");dc("/dev/stdin",0);dc("/dev/stdout",1);dc("/dev/stderr",1)}Cb=!1;Oa(ra);Oa(sa);h.onRuntimeInitialized?.();h.noInitialRun||Ff(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=
h.postRun.shift();ta.unshift(e)}Oa(ta)}}if(0<va)wa=Gf;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ua();Oa(qa);0<va?wa=Gf:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();Gf();
